/********************************************************************
* _ROOT_DICT_Algorithm.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error _ROOT_DICT_Algorithm.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable_ROOT_DICT_Algorithm();
extern void G__cpp_setup_inheritance_ROOT_DICT_Algorithm();
extern void G__cpp_setup_typetable_ROOT_DICT_Algorithm();
extern void G__cpp_setup_memvar_ROOT_DICT_Algorithm();
extern void G__cpp_setup_global_ROOT_DICT_Algorithm();
extern void G__cpp_setup_memfunc_ROOT_DICT_Algorithm();
extern void G__cpp_setup_func_ROOT_DICT_Algorithm();
extern void G__set_cpp_environment_ROOT_DICT_Algorithm();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "AlgConfigPool.h"
#include "AlgFactory.h"
#include "AlgId.h"
#include "Algorithm.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_string;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_genie;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_geniecLcLEAlgStatus;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_geniecLcLAlgStatus;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_geniecLcLEAlgCmp;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_geniecLcLAlgCmp;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_TVectorTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_TVectorTlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_RgAlg;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_geniecLcLAlgId;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_geniecLcLERgType;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_pairlEstringcOgeniecLcLRegistryItemImUgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_geniecLcLRegistry;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_geniecLcLAlgorithm;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_pairlEstringcOgeniecLcLAlgorithmmUgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_geniecLcLAlgConfigPool;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_maplEstringcOgeniecLcLRegistrymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistrymUgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_AlgorithmLN_geniecLcLAlgFactory;

/* STUB derived class for protected member access */
