//
// File generated by rootcint at Thu Jul 13 14:24:03 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME _ROOT_DICT_BaryonResonance
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "_ROOT_DICT_BaryonResonance.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace genie {
   namespace ROOTDict {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void genie_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("genie", 0 /*version*/, "./BaryonResUtils.h", 28,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &genie_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void genie_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

namespace ROOTDict {
   void geniecLcLBaryonResList_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void geniecLcLBaryonResList_Dictionary();
   static void *new_geniecLcLBaryonResList(void *p = 0);
   static void *newArray_geniecLcLBaryonResList(Long_t size, void *p);
   static void delete_geniecLcLBaryonResList(void *p);
   static void deleteArray_geniecLcLBaryonResList(void *p);
   static void destruct_geniecLcLBaryonResList(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::genie::BaryonResList*)
   {
      ::genie::BaryonResList *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::genie::BaryonResList),0);
      static ::ROOT::TGenericClassInfo 
         instance("genie::BaryonResList", "./BaryonResList.h", 35,
                  typeid(::genie::BaryonResList), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &geniecLcLBaryonResList_Dictionary, isa_proxy, 0,
                  sizeof(::genie::BaryonResList) );
      instance.SetNew(&new_geniecLcLBaryonResList);
      instance.SetNewArray(&newArray_geniecLcLBaryonResList);
      instance.SetDelete(&delete_geniecLcLBaryonResList);
      instance.SetDeleteArray(&deleteArray_geniecLcLBaryonResList);
      instance.SetDestructor(&destruct_geniecLcLBaryonResList);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::genie::BaryonResList*)
   {
      return GenerateInitInstanceLocal((::genie::BaryonResList*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::genie::BaryonResList*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void geniecLcLBaryonResList_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::genie::BaryonResList*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace genie {
namespace utils {
   namespace ROOTDict {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void geniecLcLutils_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("genie::utils", 0 /*version*/, "./BaryonResUtils.h", 30,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &geniecLcLutils_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void geniecLcLutils_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}
}

namespace genie {
namespace utils {
namespace res {
   namespace ROOTDict {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void geniecLcLutilscLcLres_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("genie::utils::res", 0 /*version*/, "./BaryonResUtils.h", 31,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &geniecLcLutilscLcLres_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void geniecLcLutilscLcLres_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}
}
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_geniecLcLBaryonResList(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genie::BaryonResList : new ::genie::BaryonResList;
   }
   static void *newArray_geniecLcLBaryonResList(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genie::BaryonResList[nElements] : new ::genie::BaryonResList[nElements];
   }
   // Wrapper around operator delete
   static void delete_geniecLcLBaryonResList(void *p) {
      delete ((::genie::BaryonResList*)p);
   }
   static void deleteArray_geniecLcLBaryonResList(void *p) {
      delete [] ((::genie::BaryonResList*)p);
   }
   static void destruct_geniecLcLBaryonResList(void *p) {
      typedef ::genie::BaryonResList current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::genie::BaryonResList

/********************************************************
* _ROOT_DICT_BaryonResonance.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtable_ROOT_DICT_BaryonResonance();

extern "C" void G__set_cpp_environment_ROOT_DICT_BaryonResonance() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("BaryonResList.h");
  G__add_compiledheader("BaryonResUtils.h");
  G__cpp_reset_tagtable_ROOT_DICT_BaryonResonance();
}
#include <new>
extern "C" int G__cpp_dllrev_ROOT_DICT_BaryonResonance() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* genie */
static int G___ROOT_DICT_BaryonResonance_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::BaryonResList*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}


/* genie::BaryonResList */
static int G___ROOT_DICT_BaryonResonance_170_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::BaryonResList* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genie::BaryonResList[n];
     } else {
       p = new((void*) gvp) genie::BaryonResList[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genie::BaryonResList;
     } else {
       p = new((void*) gvp) genie::BaryonResList;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLBaryonResList));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_170_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::BaryonResList* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new genie::BaryonResList(*(genie::BaryonResList*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) genie::BaryonResList(*(genie::BaryonResList*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLBaryonResList));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_170_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((genie::BaryonResList*) G__getstructoffset())->DecodeFromNameList(*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      ((genie::BaryonResList*) G__getstructoffset())->DecodeFromNameList(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_170_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const genie::BaryonResList*) G__getstructoffset())->NResonances());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_170_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string* pobj;
         const string xobj = ((const genie::BaryonResList*) G__getstructoffset())->ResonanceName((unsigned int) G__int(libp->para[0]));
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_170_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const genie::BaryonResList*) G__getstructoffset())->ResonanceId((unsigned int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_170_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const genie::BaryonResList*) G__getstructoffset())->ResonancePdgCode((unsigned int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_170_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const genie::BaryonResList*) G__getstructoffset())->Find((genie::Resonance_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_170_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genie::BaryonResList*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_170_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genie::BaryonResList*) G__getstructoffset())->Copy(*(genie::BaryonResList*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_170_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const genie::BaryonResList*) G__getstructoffset())->Print(*(ostream*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef genie::BaryonResList G__TgeniecLcLBaryonResList;
static int G___ROOT_DICT_BaryonResonance_170_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (genie::BaryonResList*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((genie::BaryonResList*) (soff+(sizeof(genie::BaryonResList)*i)))->~G__TgeniecLcLBaryonResList();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (genie::BaryonResList*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((genie::BaryonResList*) (soff))->~G__TgeniecLcLBaryonResList();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G___ROOT_DICT_BaryonResonance_170_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::BaryonResList* dest = (genie::BaryonResList*) G__getstructoffset();
   *dest = *(genie::BaryonResList*) libp->para[0].ref;
   const genie::BaryonResList& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* genie::utils */

/* genie::utils::res */
static int G___ROOT_DICT_BaryonResonance_176_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) genie::utils::res::AsString((genie::Resonance_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_176_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) genie::utils::res::FromString((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_176_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) genie::utils::res::PdgCode((genie::Resonance_t) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_176_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) genie::utils::res::FromPdgCode((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_176_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) genie::utils::res::IsBaryonResonance((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_176_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) genie::utils::res::IsDelta((genie::Resonance_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_176_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) genie::utils::res::IsN((genie::Resonance_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_176_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) genie::utils::res::Mass((genie::Resonance_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_176_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) genie::utils::res::Width((genie::Resonance_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_176_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) genie::utils::res::BWNorm((genie::Resonance_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_176_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) genie::utils::res::OrbitalAngularMom((genie::Resonance_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BaryonResonance_176_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) genie::utils::res::ResonanceIndex((genie::Resonance_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* genie */

/* genie::BaryonResList */

/* genie::utils */

/* genie::utils::res */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunc_ROOT_DICT_BaryonResonance {
 public:
  G__Sizep2memfunc_ROOT_DICT_BaryonResonance(): p(&G__Sizep2memfunc_ROOT_DICT_BaryonResonance::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunc_ROOT_DICT_BaryonResonance::*p)();
};

size_t G__get_sizep2memfunc_ROOT_DICT_BaryonResonance()
{
  G__Sizep2memfunc_ROOT_DICT_BaryonResonance a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritance_ROOT_DICT_BaryonResonance() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetable_ROOT_DICT_BaryonResonance() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Resonance_t",117,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),0,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Resonance_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_vectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_vectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_vectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<genie::EResonance>",117,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_vectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* genie */
static void G__setup_memvargenie(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_genie));
   {
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kNoResonance=%lldLL",(long long)genie::kNoResonance).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kP33_1232=%lldLL",(long long)genie::kP33_1232).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kS11_1535=%lldLL",(long long)genie::kS11_1535).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kD13_1520=%lldLL",(long long)genie::kD13_1520).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kS11_1650=%lldLL",(long long)genie::kS11_1650).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kD13_1700=%lldLL",(long long)genie::kD13_1700).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kD15_1675=%lldLL",(long long)genie::kD15_1675).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kS31_1620=%lldLL",(long long)genie::kS31_1620).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kD33_1700=%lldLL",(long long)genie::kD33_1700).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kP11_1440=%lldLL",(long long)genie::kP11_1440).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kP33_1600=%lldLL",(long long)genie::kP33_1600).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kP13_1720=%lldLL",(long long)genie::kP13_1720).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kF15_1680=%lldLL",(long long)genie::kF15_1680).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kP31_1910=%lldLL",(long long)genie::kP31_1910).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kP33_1920=%lldLL",(long long)genie::kP33_1920).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kF35_1905=%lldLL",(long long)genie::kF35_1905).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kF37_1950=%lldLL",(long long)genie::kF37_1950).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kP11_1710=%lldLL",(long long)genie::kP11_1710).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kF17_1970=%lldLL",(long long)genie::kF17_1970).data(),0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* genie::BaryonResList */
static void G__setup_memvargeniecLcLBaryonResList(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLBaryonResList));
   { genie::BaryonResList *p; p=(genie::BaryonResList*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_vectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgR),G__defined_typename("vector<Resonance_t>"),-1,4,"fResVec=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* genie::utils */
static void G__setup_memvargeniecLcLutils(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLutils));
   {
   }
   G__tag_memvar_reset();
}


   /* genie::utils::res */
static void G__setup_memvargeniecLcLutilscLcLres(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLutilscLcLres));
   {
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvar_ROOT_DICT_BaryonResonance() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncgenie(void) {
   /* genie */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_genie));
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_BaryonResonance_168_0_1, 117, G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::BaryonResList' - 11 - rl", (char*)NULL, (void*) G__func2void( (ostream& (*)(ostream&, const genie::BaryonResList&))(&genie::operator<<) ), 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncgeniecLcLBaryonResList(void) {
   /* genie::BaryonResList */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLBaryonResList));
   G__memfunc_setup("BaryonResList",1329,G___ROOT_DICT_BaryonResonance_170_0_1, 105, G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLBaryonResList), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BaryonResList",1329,G___ROOT_DICT_BaryonResonance_170_0_2, 105, G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLBaryonResList), -1, 0, 1, 1, 1, 0, "u 'genie::BaryonResList' - 11 - rl", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DecodeFromNameList",1781,G___ROOT_DICT_BaryonResonance_170_0_3, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 0 - list u 'string' - 0 '\",\"' delimiter", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NResonances",1119,G___ROOT_DICT_BaryonResonance_170_0_4, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ResonanceName",1311,G___ROOT_DICT_BaryonResonance_170_0_5, 117, G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_string), -1, 0, 1, 1, 1, 8, "h - - 0 - ires", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ResonanceId",1099,G___ROOT_DICT_BaryonResonance_170_0_6, 105, G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance), G__defined_typename("genie::Resonance_t"), 0, 1, 1, 1, 8, "h - - 0 - ires", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ResonancePdgCode",1588,G___ROOT_DICT_BaryonResonance_170_0_7, 105, -1, -1, 0, 1, 1, 1, 8, "h - - 0 - ires", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Find",385,G___ROOT_DICT_BaryonResonance_170_0_8, 103, -1, -1, 0, 1, 1, 1, 8, "u 'genie::EResonance' 'genie::Resonance_t' 0 - res", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G___ROOT_DICT_BaryonResonance_170_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Copy",411,G___ROOT_DICT_BaryonResonance_170_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'genie::BaryonResList' - 11 - rl", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G___ROOT_DICT_BaryonResonance_170_0_11, 121, -1, -1, 0, 1, 1, 1, 8, "u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BaryonResList", 1455, G___ROOT_DICT_BaryonResonance_170_0_12, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G___ROOT_DICT_BaryonResonance_170_0_13, (int) ('u'), G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLBaryonResList), -1, 1, 1, 1, 1, 0, "u 'genie::BaryonResList' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncgeniecLcLutils(void) {
   /* genie::utils */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLutils));
   G__tag_memfunc_reset();
}

static void G__setup_memfuncgeniecLcLutilscLcLres(void) {
   /* genie::utils::res */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLutilscLcLres));
   G__memfunc_setup("AsString",811,G___ROOT_DICT_BaryonResonance_176_0_1, 67, -1, -1, 0, 1, 1, 1, 1, "u 'genie::EResonance' 'genie::Resonance_t' 0 - res", "/< resonance id -> string", (void*) G__func2void( (const char* (*)(genie::Resonance_t))(&genie::utils::res::AsString) ), 0);
   G__memfunc_setup("FromString",1035,G___ROOT_DICT_BaryonResonance_176_0_2, 105, G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance), G__defined_typename("genie::Resonance_t"), 0, 1, 1, 1, 0, "C - - 10 - res", "/< string -> resonance id", (void*) G__func2void( (genie::Resonance_t (*)(const char*))(&genie::utils::res::FromString) ), 0);
   G__memfunc_setup("PdgCode",662,G___ROOT_DICT_BaryonResonance_176_0_3, 105, -1, -1, 0, 2, 1, 1, 0, 
"u 'genie::EResonance' 'genie::Resonance_t' 0 - res i - - 0 - Q", "/< (resonance id, charge) -> PDG code", (void*) G__func2void( (int (*)(genie::Resonance_t, int))(&genie::utils::res::PdgCode) ), 0);
   G__memfunc_setup("FromPdgCode",1066,G___ROOT_DICT_BaryonResonance_176_0_4, 105, G__get_linked_tagnum(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance), G__defined_typename("genie::Resonance_t"), 0, 1, 1, 1, 0, "i - - 0 - pdgc", "/< PDG code -> resonance id", (void*) G__func2void( (genie::Resonance_t (*)(int))(&genie::utils::res::FromPdgCode) ), 0);
   G__memfunc_setup("IsBaryonResonance",1733,G___ROOT_DICT_BaryonResonance_176_0_5, 103, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - pdgc", "/< is input a baryon resonance?", (void*) G__func2void( (bool (*)(int))(&genie::utils::res::IsBaryonResonance) ), 0);
   G__memfunc_setup("IsDelta",678,G___ROOT_DICT_BaryonResonance_176_0_6, 103, -1, -1, 0, 1, 1, 1, 0, "u 'genie::EResonance' 'genie::Resonance_t' 0 - res", "/< is it a Delta resonance?", (void*) G__func2void( (bool (*)(genie::Resonance_t))(&genie::utils::res::IsDelta) ), 0);
   G__memfunc_setup("IsN",266,G___ROOT_DICT_BaryonResonance_176_0_7, 103, -1, -1, 0, 1, 1, 1, 0, "u 'genie::EResonance' 'genie::Resonance_t' 0 - res", "/< is it an N resonance?", (void*) G__func2void( (bool (*)(genie::Resonance_t))(&genie::utils::res::IsN) ), 0);
   G__memfunc_setup("Mass",404,G___ROOT_DICT_BaryonResonance_176_0_8, 100, -1, -1, 0, 1, 1, 1, 0, "u 'genie::EResonance' 'genie::Resonance_t' 0 - res", "/< resonance mass (GeV)", (void*) G__func2void( (double (*)(genie::Resonance_t))(&genie::utils::res::Mass) ), 0);
   G__memfunc_setup("Width",512,G___ROOT_DICT_BaryonResonance_176_0_9, 100, -1, -1, 0, 1, 1, 1, 0, "u 'genie::EResonance' 'genie::Resonance_t' 0 - res", "/< resonance width (GeV)", (void*) G__func2void( (double (*)(genie::Resonance_t))(&genie::utils::res::Width) ), 0);
   G__memfunc_setup("BWNorm",565,G___ROOT_DICT_BaryonResonance_176_0_10, 100, -1, -1, 0, 1, 1, 1, 0, "u 'genie::EResonance' 'genie::Resonance_t' 0 - res", "/< breit-wigner normalization factor", (void*) G__func2void( (double (*)(genie::Resonance_t))(&genie::utils::res::BWNorm) ), 0);
   G__memfunc_setup("OrbitalAngularMom",1728,G___ROOT_DICT_BaryonResonance_176_0_11, 105, -1, -1, 0, 1, 1, 1, 0, "u 'genie::EResonance' 'genie::Resonance_t' 0 - res", "/< orbital angular momentum", (void*) G__func2void( (int (*)(genie::Resonance_t))(&genie::utils::res::OrbitalAngularMom) ), 0);
   G__memfunc_setup("ResonanceIndex",1430,G___ROOT_DICT_BaryonResonance_176_0_12, 105, -1, -1, 0, 1, 1, 1, 0, "u 'genie::EResonance' 'genie::Resonance_t' 0 - res", "/< resonance idx, quark model / SU(6)", (void*) G__func2void( (int (*)(genie::Resonance_t))(&genie::utils::res::ResonanceIndex) ), 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunc_ROOT_DICT_BaryonResonance() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_global_ROOT_DICT_BaryonResonance() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_func_ROOT_DICT_BaryonResonance() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR = { "basic_ostream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_string = { "string" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_genie = { "genie" , 110 , -1 };
G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance = { "genie::EResonance" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_geniecLcLBaryonResList = { "genie::BaryonResList" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_vectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgR = { "vector<genie::EResonance,allocator<genie::EResonance> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<genie::EResonance,allocator<genie::EResonance> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_geniecLcLutils = { "genie::utils" , 110 , -1 };
G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_geniecLcLutilscLcLres = { "genie::utils::res" , 110 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtable_ROOT_DICT_BaryonResonance() {
  G___ROOT_DICT_BaryonResonanceLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G___ROOT_DICT_BaryonResonanceLN_string.tagnum = -1 ;
  G___ROOT_DICT_BaryonResonanceLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_BaryonResonanceLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_BaryonResonanceLN_genie.tagnum = -1 ;
  G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance.tagnum = -1 ;
  G___ROOT_DICT_BaryonResonanceLN_geniecLcLBaryonResList.tagnum = -1 ;
  G___ROOT_DICT_BaryonResonanceLN_vectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgR.tagnum = -1 ;
  G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_BaryonResonanceLN_geniecLcLutils.tagnum = -1 ;
  G___ROOT_DICT_BaryonResonanceLN_geniecLcLutilscLcLres.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtable_ROOT_DICT_BaryonResonance() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BaryonResonanceLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BaryonResonanceLN_string);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BaryonResonanceLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BaryonResonanceLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_BaryonResonanceLN_genie),0,-1,0,(char*)NULL,G__setup_memvargenie,G__setup_memfuncgenie);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLBaryonResList),sizeof(genie::BaryonResList),-1,1792,(char*)NULL,G__setup_memvargeniecLcLBaryonResList,G__setup_memfuncgeniecLcLBaryonResList);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BaryonResonanceLN_vectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLutils),0,-1,0,(char*)NULL,G__setup_memvargeniecLcLutils,G__setup_memfuncgeniecLcLutils);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_BaryonResonanceLN_geniecLcLutilscLcLres),0,-1,0,(char*)NULL,G__setup_memvargeniecLcLutilscLcLres,G__setup_memfuncgeniecLcLutilscLcLres);
}
extern "C" void G__cpp_setup_ROOT_DICT_BaryonResonance(void) {
  G__check_setup_version(30051515,"G__cpp_setup_ROOT_DICT_BaryonResonance()");
  G__set_cpp_environment_ROOT_DICT_BaryonResonance();
  G__cpp_setup_tagtable_ROOT_DICT_BaryonResonance();

  G__cpp_setup_inheritance_ROOT_DICT_BaryonResonance();

  G__cpp_setup_typetable_ROOT_DICT_BaryonResonance();

  G__cpp_setup_memvar_ROOT_DICT_BaryonResonance();

  G__cpp_setup_memfunc_ROOT_DICT_BaryonResonance();
  G__cpp_setup_global_ROOT_DICT_BaryonResonance();
  G__cpp_setup_func_ROOT_DICT_BaryonResonance();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunc_ROOT_DICT_BaryonResonance();
  return;
}
class G__cpp_setup_init_ROOT_DICT_BaryonResonance {
  public:
    G__cpp_setup_init_ROOT_DICT_BaryonResonance() { G__add_setup_func("_ROOT_DICT_BaryonResonance",(G__incsetup)(&G__cpp_setup_ROOT_DICT_BaryonResonance)); G__call_setup_funcs(); }
   ~G__cpp_setup_init_ROOT_DICT_BaryonResonance() { G__remove_setup_func("_ROOT_DICT_BaryonResonance"); }
};
G__cpp_setup_init_ROOT_DICT_BaryonResonance G__cpp_setup_initializer_ROOT_DICT_BaryonResonance;

