/********************************************************************
* _ROOT_DICT_BaryonResonance.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error _ROOT_DICT_BaryonResonance.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable_ROOT_DICT_BaryonResonance();
extern void G__cpp_setup_inheritance_ROOT_DICT_BaryonResonance();
extern void G__cpp_setup_typetable_ROOT_DICT_BaryonResonance();
extern void G__cpp_setup_memvar_ROOT_DICT_BaryonResonance();
extern void G__cpp_setup_global_ROOT_DICT_BaryonResonance();
extern void G__cpp_setup_memfunc_ROOT_DICT_BaryonResonance();
extern void G__cpp_setup_func_ROOT_DICT_BaryonResonance();
extern void G__set_cpp_environment_ROOT_DICT_BaryonResonance();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BaryonResList.h"
#include "BaryonResUtils.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_string;
extern G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_genie;
extern G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_geniecLcLEResonance;
extern G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_geniecLcLBaryonResList;
extern G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_vectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgR;
extern G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_reverse_iteratorlEvectorlEgeniecLcLEResonancecOallocatorlEgeniecLcLEResonancegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_geniecLcLutils;
extern G__linked_taginfo G___ROOT_DICT_BaryonResonanceLN_geniecLcLutilscLcLres;

/* STUB derived class for protected member access */
