//____________________________________________________________________________
/*!

\class    genie::RESNCGammaInteractionListGenerator

\brief    Concrete implementations of the InteractionListGeneratorI interface.
          Generates a list of all the interactions that can be generated by the 
          RESNCGAMMA EventGenerator.

\author   Pierre Lasorak <p.j.j.lasorak \at qmul.ac.uk>
          Queen Mary University, London

\created  November 24, 2015

\cpright  Copyright (c) 2003-2015, GENIE Neutrino MC Generator Collaboration
          For the full text of the license visit http://copyright.genie-mc.org
          or see $GENIE/LICENSE
*/
//____________________________________________________________________________

#ifndef _RESNCGAMMA_INTERACTION_GENERATOR_H_
#define _RESNCGAMMA_INTERACTION_GENERATOR_H_

#include "EVGCore/InteractionListGeneratorI.h"

namespace genie {

class RESNCGammaInteractionListGenerator : public InteractionListGeneratorI {

public :
  RESNCGammaInteractionListGenerator();
  RESNCGammaInteractionListGenerator(string config);
 ~RESNCGammaInteractionListGenerator();

  //-- implement the InteractionListGeneratorI interface
  InteractionList * CreateInteractionList(const InitialState & init) const;
};

}      // genie namespace
#endif // _RESNCGAMMA_INTERACTION_GENERATOR_H_
