//
// File generated by rootcint at Thu Jul 13 14:26:54 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME _ROOT_DICT_PDF
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "_ROOT_DICT_PDF.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace genie {
   namespace ROOTDict {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void genie_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("genie", 0 /*version*/, "./PDFLIB.h", 25,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &genie_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void genie_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

namespace ROOTDict {
   void geniecLcLPDFModelI_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void geniecLcLPDFModelI_Dictionary();
   static void delete_geniecLcLPDFModelI(void *p);
   static void deleteArray_geniecLcLPDFModelI(void *p);
   static void destruct_geniecLcLPDFModelI(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::genie::PDFModelI*)
   {
      ::genie::PDFModelI *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::genie::PDFModelI),0);
      static ::ROOT::TGenericClassInfo 
         instance("genie::PDFModelI", "/users/mouland/Documents/GENIE_NCGamma/src//PDF/PDFModelI.h", 33,
                  typeid(::genie::PDFModelI), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &geniecLcLPDFModelI_Dictionary, isa_proxy, 0,
                  sizeof(::genie::PDFModelI) );
      instance.SetDelete(&delete_geniecLcLPDFModelI);
      instance.SetDeleteArray(&deleteArray_geniecLcLPDFModelI);
      instance.SetDestructor(&destruct_geniecLcLPDFModelI);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::genie::PDFModelI*)
   {
      return GenerateInitInstanceLocal((::genie::PDFModelI*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::genie::PDFModelI*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void geniecLcLPDFModelI_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::genie::PDFModelI*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   void geniecLcLPDF_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void geniecLcLPDF_Dictionary();
   static void *new_geniecLcLPDF(void *p = 0);
   static void *newArray_geniecLcLPDF(Long_t size, void *p);
   static void delete_geniecLcLPDF(void *p);
   static void deleteArray_geniecLcLPDF(void *p);
   static void destruct_geniecLcLPDF(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::genie::PDF*)
   {
      ::genie::PDF *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::genie::PDF),0);
      static ::ROOT::TGenericClassInfo 
         instance("genie::PDF", "./PDF.h", 35,
                  typeid(::genie::PDF), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &geniecLcLPDF_Dictionary, isa_proxy, 0,
                  sizeof(::genie::PDF) );
      instance.SetNew(&new_geniecLcLPDF);
      instance.SetNewArray(&newArray_geniecLcLPDF);
      instance.SetDelete(&delete_geniecLcLPDF);
      instance.SetDeleteArray(&deleteArray_geniecLcLPDF);
      instance.SetDestructor(&destruct_geniecLcLPDF);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::genie::PDF*)
   {
      return GenerateInitInstanceLocal((::genie::PDF*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::genie::PDF*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void geniecLcLPDF_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::genie::PDF*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   void geniecLcLPDFLIB_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void geniecLcLPDFLIB_Dictionary();
   static void *new_geniecLcLPDFLIB(void *p = 0);
   static void *newArray_geniecLcLPDFLIB(Long_t size, void *p);
   static void delete_geniecLcLPDFLIB(void *p);
   static void deleteArray_geniecLcLPDFLIB(void *p);
   static void destruct_geniecLcLPDFLIB(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::genie::PDFLIB*)
   {
      ::genie::PDFLIB *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::genie::PDFLIB),0);
      static ::ROOT::TGenericClassInfo 
         instance("genie::PDFLIB", "./PDFLIB.h", 27,
                  typeid(::genie::PDFLIB), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &geniecLcLPDFLIB_Dictionary, isa_proxy, 0,
                  sizeof(::genie::PDFLIB) );
      instance.SetNew(&new_geniecLcLPDFLIB);
      instance.SetNewArray(&newArray_geniecLcLPDFLIB);
      instance.SetDelete(&delete_geniecLcLPDFLIB);
      instance.SetDeleteArray(&deleteArray_geniecLcLPDFLIB);
      instance.SetDestructor(&destruct_geniecLcLPDFLIB);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::genie::PDFLIB*)
   {
      return GenerateInitInstanceLocal((::genie::PDFLIB*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::genie::PDFLIB*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void geniecLcLPDFLIB_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::genie::PDFLIB*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_geniecLcLPDF(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genie::PDF : new ::genie::PDF;
   }
   static void *newArray_geniecLcLPDF(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genie::PDF[nElements] : new ::genie::PDF[nElements];
   }
   // Wrapper around operator delete
   static void delete_geniecLcLPDF(void *p) {
      delete ((::genie::PDF*)p);
   }
   static void deleteArray_geniecLcLPDF(void *p) {
      delete [] ((::genie::PDF*)p);
   }
   static void destruct_geniecLcLPDF(void *p) {
      typedef ::genie::PDF current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::genie::PDF

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_geniecLcLPDFModelI(void *p) {
      delete ((::genie::PDFModelI*)p);
   }
   static void deleteArray_geniecLcLPDFModelI(void *p) {
      delete [] ((::genie::PDFModelI*)p);
   }
   static void destruct_geniecLcLPDFModelI(void *p) {
      typedef ::genie::PDFModelI current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::genie::PDFModelI

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_geniecLcLPDFLIB(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genie::PDFLIB : new ::genie::PDFLIB;
   }
   static void *newArray_geniecLcLPDFLIB(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genie::PDFLIB[nElements] : new ::genie::PDFLIB[nElements];
   }
   // Wrapper around operator delete
   static void delete_geniecLcLPDFLIB(void *p) {
      delete ((::genie::PDFLIB*)p);
   }
   static void deleteArray_geniecLcLPDFLIB(void *p) {
      delete [] ((::genie::PDFLIB*)p);
   }
   static void destruct_geniecLcLPDFLIB(void *p) {
      typedef ::genie::PDFLIB current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::genie::PDFLIB

/********************************************************
* _ROOT_DICT_PDF.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtable_ROOT_DICT_PDF();

extern "C" void G__set_cpp_environment_ROOT_DICT_PDF() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("PDF.h");
  G__add_compiledheader("PDFLIB.h");
  G__add_compiledheader("PDFModelI.h");
  G__cpp_reset_tagtable_ROOT_DICT_PDF();
}
#include <new>
extern "C" int G__cpp_dllrev_ROOT_DICT_PDF() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* genie */
static int G___ROOT_DICT_PDF_403_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::AlgId*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_403_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::Registry*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_403_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::Algorithm*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_403_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::PDF*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}


/* genie::PDFModelI */
static int G___ROOT_DICT_PDF_561_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDFModelI*) G__getstructoffset())->UpValence((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_561_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDFModelI*) G__getstructoffset())->DownValence((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_561_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDFModelI*) G__getstructoffset())->UpSea((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_561_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDFModelI*) G__getstructoffset())->DownSea((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_561_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDFModelI*) G__getstructoffset())->Strange((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_561_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDFModelI*) G__getstructoffset())->Charm((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_561_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDFModelI*) G__getstructoffset())->Bottom((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_561_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDFModelI*) G__getstructoffset())->Top((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_561_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDFModelI*) G__getstructoffset())->Gluon((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_561_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const genie::PDF_t* pobj;
         const genie::PDF_t xobj = ((const genie::PDFModelI*) G__getstructoffset())->AllPDFs((double) G__double(libp->para[0]), (double) G__double(libp->para[1]));
         pobj = new genie::PDF_t(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef genie::PDFModelI G__TgeniecLcLPDFModelI;
static int G___ROOT_DICT_PDF_561_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (genie::PDFModelI*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((genie::PDFModelI*) (soff+(sizeof(genie::PDFModelI)*i)))->~G__TgeniecLcLPDFModelI();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (genie::PDFModelI*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((genie::PDFModelI*) (soff))->~G__TgeniecLcLPDFModelI();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G___ROOT_DICT_PDF_561_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::PDFModelI* dest = (genie::PDFModelI*) G__getstructoffset();
   *dest = *(genie::PDFModelI*) libp->para[0].ref;
   const genie::PDFModelI& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* genie::PDF */
static int G___ROOT_DICT_PDF_562_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::PDF* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genie::PDF[n];
     } else {
       p = new((void*) gvp) genie::PDF[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genie::PDF;
     } else {
       p = new((void*) gvp) genie::PDF;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDF));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::PDF* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new genie::PDF(*(genie::PDF*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) genie::PDF(*(genie::PDF*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDF));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genie::PDF*) G__getstructoffset())->SetModel((genie::PDFModelI*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genie::PDF*) G__getstructoffset())->Calculate((double) G__double(libp->para[0]), (double) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDF*) G__getstructoffset())->UpValence());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDF*) G__getstructoffset())->DownValence());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDF*) G__getstructoffset())->UpSea());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDF*) G__getstructoffset())->DownSea());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDF*) G__getstructoffset())->Strange());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDF*) G__getstructoffset())->Charm());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDF*) G__getstructoffset())->Bottom());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDF*) G__getstructoffset())->Top());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::PDF*) G__getstructoffset())->Gluon());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genie::PDF*) G__getstructoffset())->ScaleValence((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genie::PDF*) G__getstructoffset())->ScaleSea((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genie::PDF*) G__getstructoffset())->ScaleUpValence((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genie::PDF*) G__getstructoffset())->ScaleDownValence((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genie::PDF*) G__getstructoffset())->ScaleUpSea((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genie::PDF*) G__getstructoffset())->ScaleDownSea((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genie::PDF*) G__getstructoffset())->ScaleStrange((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genie::PDF*) G__getstructoffset())->ScaleCharm((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genie::PDF*) G__getstructoffset())->Reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genie::PDF*) G__getstructoffset())->Copy(*(genie::PDF*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_562_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const genie::PDF*) G__getstructoffset())->Print(*(ostream*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef genie::PDF G__TgeniecLcLPDF;
static int G___ROOT_DICT_PDF_562_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (genie::PDF*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((genie::PDF*) (soff+(sizeof(genie::PDF)*i)))->~G__TgeniecLcLPDF();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (genie::PDF*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((genie::PDF*) (soff))->~G__TgeniecLcLPDF();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* genie::PDFLIB */
static int G___ROOT_DICT_PDF_563_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::PDFLIB* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genie::PDFLIB[n];
     } else {
       p = new((void*) gvp) genie::PDFLIB[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genie::PDFLIB;
     } else {
       p = new((void*) gvp) genie::PDFLIB;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFLIB));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_PDF_563_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::PDFLIB* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new genie::PDFLIB(*((string*) G__int(libp->para[0])));
   } else {
     p = new((void*) gvp) genie::PDFLIB(*((string*) G__int(libp->para[0])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFLIB));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G___ROOT_DICT_PDF_563_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   genie::PDFLIB* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new genie::PDFLIB(*(genie::PDFLIB*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFLIB));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef genie::PDFLIB G__TgeniecLcLPDFLIB;
static int G___ROOT_DICT_PDF_563_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (genie::PDFLIB*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((genie::PDFLIB*) (soff+(sizeof(genie::PDFLIB)*i)))->~G__TgeniecLcLPDFLIB();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (genie::PDFLIB*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((genie::PDFLIB*) (soff))->~G__TgeniecLcLPDFLIB();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G___ROOT_DICT_PDF_563_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::PDFLIB* dest = (genie::PDFLIB*) G__getstructoffset();
   *dest = *(genie::PDFLIB*) libp->para[0].ref;
   const genie::PDFLIB& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* genie */

/* genie::PDFModelI */

/* genie::PDF */

/* genie::PDFLIB */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunc_ROOT_DICT_PDF {
 public:
  G__Sizep2memfunc_ROOT_DICT_PDF(): p(&G__Sizep2memfunc_ROOT_DICT_PDF::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunc_ROOT_DICT_PDF::*p)();
};

size_t G__get_sizep2memfunc_ROOT_DICT_PDF()
{
  G__Sizep2memfunc_ROOT_DICT_PDF a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritance_ROOT_DICT_PDF() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFModelI))) {
     genie::PDFModelI *G__Lderived;
     G__Lderived=(genie::PDFModelI*)0x1000;
     {
       genie::Algorithm *G__Lpbase=(genie::Algorithm*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFModelI),G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLAlgorithm),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFLIB))) {
     genie::PDFLIB *G__Lderived;
     G__Lderived=(genie::PDFLIB*)0x1000;
     {
       genie::PDFModelI *G__Lpbase=(genie::PDFModelI*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFLIB),G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFModelI),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       genie::Algorithm *G__Lpbase=(genie::Algorithm*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFLIB),G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLAlgorithm),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetable_ROOT_DICT_PDF() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgStatus_t",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLEAlgStatus),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgCmp_t",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLEAlgCmp),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgType_t",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLERgType),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<RgKey,RegistryItemI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,genie::RegistryItemI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,genie::RegistryItemI*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMap",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<RgKey,RegistryItemI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_pairlEstringcOgeniecLcLRegistryItemImUgR),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMapPair",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_pairlEstringcOgeniecLcLRegistryItemImUgR),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMapSizeType",107,-1,0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMapIter",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMapConstIter",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<RgKey>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgKeyList",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_vectorlEstringcOallocatorlEstringgRsPgR),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,Algorithm*>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,genie::Algorithm*>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,genie::Algorithm*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgMap",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgMapIter",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgMapConstIter",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<string,Algorithm*>",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_pairlEstringcOgeniecLcLAlgorithmmUgR),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgMapPair",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_pairlEstringcOgeniecLcLAlgorithmmUgR),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("PDF_t",117,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLEPDF),0,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* genie */
static void G__setup_memvargenie(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   {
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLEAlgStatus),-1,-2,1,G__FastAllocString(2048).Format("kAlgUndefinedStatus=%lldLL",(long long)genie::kAlgUndefinedStatus).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLEAlgStatus),-1,-2,1,G__FastAllocString(2048).Format("kAlgFail=%lldLL",(long long)genie::kAlgFail).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLEAlgStatus),-1,-2,1,G__FastAllocString(2048).Format("kAlgSuccess=%lldLL",(long long)genie::kAlgSuccess).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLEAlgCmp),-1,-2,1,G__FastAllocString(2048).Format("kAlgCmpUnknown=%lldLL",(long long)genie::kAlgCmpUnknown).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLEAlgCmp),-1,-2,1,G__FastAllocString(2048).Format("kAlgCmpIdentical=%lldLL",(long long)genie::kAlgCmpIdentical).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLEAlgCmp),-1,-2,1,G__FastAllocString(2048).Format("kAlgCmpDiffConfig=%lldLL",(long long)genie::kAlgCmpDiffConfig).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLEAlgCmp),-1,-2,1,G__FastAllocString(2048).Format("kAlgCmpDiffAlg=%lldLL",(long long)genie::kAlgCmpDiffAlg).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgUndefined=%lldLL",(long long)genie::kRgUndefined).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgBool=%lldLL",(long long)genie::kRgBool).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgInt=%lldLL",(long long)genie::kRgInt).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgDbl=%lldLL",(long long)genie::kRgDbl).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgStr=%lldLL",(long long)genie::kRgStr).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgAlg=%lldLL",(long long)genie::kRgAlg).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgH1F=%lldLL",(long long)genie::kRgH1F).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgH2F=%lldLL",(long long)genie::kRgH2F).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgTree=%lldLL",(long long)genie::kRgTree).data(),0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* genie::PDFModelI */
static void G__setup_memvargeniecLcLPDFModelI(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFModelI));
   { genie::PDFModelI *p; p=(genie::PDFModelI*)0x1000; if (p) { }
   }
   G__tag_memvar_reset();
}


   /* genie::PDF */
static void G__setup_memvargeniecLcLPDF(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDF));
   { genie::PDF *p; p=(genie::PDF*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fUpValence=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fDownValence=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fUpSea=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fDownSea=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fStrange=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fCharm=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fBottom=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fTop=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fGluon=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFModelI),-1,-1,2,"fModel=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* genie::PDFLIB */
static void G__setup_memvargeniecLcLPDFLIB(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFLIB));
   { genie::PDFLIB *p; p=(genie::PDFLIB*)0x1000; if (p) { }
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvar_ROOT_DICT_PDF() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncgenie(void) {
   /* genie */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_genie));
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_PDF_403_0_1, 117, G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::AlgId' - 11 - alg", (char*)NULL, (void*) G__func2void( (ostream& (*)(ostream&, const genie::AlgId&))(&genie::operator<<) ), 0);
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_PDF_403_0_2, 117, G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::Registry' - 11 - registry", (char*)NULL, (void*) G__func2void( (ostream& (*)(ostream&, const genie::Registry&))(&genie::operator<<) ), 0);
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_PDF_403_0_3, 117, G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::Algorithm' - 11 - alg", (char*)NULL, (void*) G__func2void( (ostream& (*)(ostream&, const genie::Algorithm&))(&genie::operator<<) ), 0);
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_PDF_403_0_4, 117, G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::PDF' - 11 - pdf_set", (char*)NULL, (void*) G__func2void( (ostream& (*)(ostream&, const genie::PDF&))(&genie::operator<<) ), 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncgeniecLcLPDFModelI(void) {
   /* genie::PDFModelI */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFModelI));
   G__memfunc_setup("UpValence",899,G___ROOT_DICT_PDF_561_0_1, 100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("DownValence",1110,G___ROOT_DICT_PDF_561_0_2, 100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("UpSea",478,G___ROOT_DICT_PDF_561_0_3, 100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("DownSea",689,G___ROOT_DICT_PDF_561_0_4, 100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("Strange",724,G___ROOT_DICT_PDF_561_0_5, 100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("Charm",491,G___ROOT_DICT_PDF_561_0_6, 100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("Bottom",629,G___ROOT_DICT_PDF_561_0_7, 100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("Top",307,G___ROOT_DICT_PDF_561_0_8, 100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("Gluon",517,G___ROOT_DICT_PDF_561_0_9, 100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("AllPDFs",614,G___ROOT_DICT_PDF_561_0_10, 117, G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLEPDF), G__defined_typename("genie::PDF_t"), 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 3);
   // automatic destructor
   G__memfunc_setup("~PDFModelI", 914, G___ROOT_DICT_PDF_561_0_14, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G___ROOT_DICT_PDF_561_0_15, (int) ('u'), G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFModelI), -1, 1, 1, 1, 1, 0, "u 'genie::PDFModelI' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncgeniecLcLPDF(void) {
   /* genie::PDF */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDF));
   G__memfunc_setup("PDF",218,G___ROOT_DICT_PDF_562_0_1, 105, G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDF), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PDF",218,G___ROOT_DICT_PDF_562_0_2, 105, G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDF), -1, 0, 1, 1, 1, 0, "u 'genie::PDF' - 11 - pdf_set", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetModel",797,G___ROOT_DICT_PDF_562_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "U 'genie::PDFModelI' - 10 - model", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Calculate",910,G___ROOT_DICT_PDF_562_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpValence",899,G___ROOT_DICT_PDF_562_0_5, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DownValence",1110,G___ROOT_DICT_PDF_562_0_6, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpSea",478,G___ROOT_DICT_PDF_562_0_7, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DownSea",689,G___ROOT_DICT_PDF_562_0_8, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Strange",724,G___ROOT_DICT_PDF_562_0_9, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Charm",491,G___ROOT_DICT_PDF_562_0_10, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Bottom",629,G___ROOT_DICT_PDF_562_0_11, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Top",307,G___ROOT_DICT_PDF_562_0_12, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Gluon",517,G___ROOT_DICT_PDF_562_0_13, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ScaleValence",1190,G___ROOT_DICT_PDF_562_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - kscale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ScaleSea",769,G___ROOT_DICT_PDF_562_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - kscale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ScaleUpValence",1387,G___ROOT_DICT_PDF_562_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - kscale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ScaleDownValence",1598,G___ROOT_DICT_PDF_562_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - kscale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ScaleUpSea",966,G___ROOT_DICT_PDF_562_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - kscale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ScaleDownSea",1177,G___ROOT_DICT_PDF_562_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - kscale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ScaleStrange",1212,G___ROOT_DICT_PDF_562_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - kscale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ScaleCharm",979,G___ROOT_DICT_PDF_562_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - kscale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reset",515,G___ROOT_DICT_PDF_562_0_22, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Copy",411,G___ROOT_DICT_PDF_562_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'genie::PDF' - 11 - pdf_set", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G___ROOT_DICT_PDF_562_0_24, 121, -1, -1, 0, 1, 1, 1, 8, "u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PDF", 344, G___ROOT_DICT_PDF_562_0_26, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncgeniecLcLPDFLIB(void) {
   /* genie::PDFLIB */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFLIB));
   G__memfunc_setup("PDFLIB",433,G___ROOT_DICT_PDF_563_0_1, 105, G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFLIB), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PDFLIB",433,G___ROOT_DICT_PDF_563_0_2, 105, G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFLIB), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - config", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpValence",899,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("DownValence",1110,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("UpSea",478,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("DownSea",689,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Strange",724,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Charm",491,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Bottom",629,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Top",307,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Gluon",517,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AllPDFs",614,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLEPDF), G__defined_typename("genie::PDF_t"), 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Configure",930,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'genie::Registry' - 11 - config", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Configure",930,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - config", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Initialize",1042,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPDFSetFromConfig",1820,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 8, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("PDFLIB", 433, G___ROOT_DICT_PDF_563_0_17, (int) ('i'), G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFLIB), -1, 0, 1, 1, 1, 0, "u 'genie::PDFLIB' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PDFLIB", 559, G___ROOT_DICT_PDF_563_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G___ROOT_DICT_PDF_563_0_19, (int) ('u'), G__get_linked_tagnum(&G___ROOT_DICT_PDFLN_geniecLcLPDFLIB), -1, 1, 1, 1, 1, 0, "u 'genie::PDFLIB' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunc_ROOT_DICT_PDF() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_global_ROOT_DICT_PDF() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_func_ROOT_DICT_PDF() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G___ROOT_DICT_PDFLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR = { "basic_ostream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_string = { "string" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_genie = { "genie" , 110 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLEAlgStatus = { "genie::EAlgStatus" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLEAlgCmp = { "genie::EAlgCmp" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLAlgId = { "genie::AlgId" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLERgType = { "genie::ERgType" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR = { "map<string,genie::RegistryItemI*,less<string>,allocator<pair<const string,genie::RegistryItemI*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_pairlEstringcOgeniecLcLRegistryItemImUgR = { "pair<string,genie::RegistryItemI*>" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator = { "map<string,genie::RegistryItemI*,less<string>,allocator<pair<const string,genie::RegistryItemI*> > >::iterator" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLRegistry = { "genie::Registry" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLAlgorithm = { "genie::Algorithm" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR = { "map<string,genie::Algorithm*,less<string>,allocator<pair<const string,genie::Algorithm*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_pairlEstringcOgeniecLcLAlgorithmmUgR = { "pair<string,genie::Algorithm*>" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator = { "map<string,genie::Algorithm*,less<string>,allocator<pair<const string,genie::Algorithm*> > >::iterator" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLEPDF = { "genie::EPDF" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLPDFModelI = { "genie::PDFModelI" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLPDF = { "genie::PDF" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLPDFLIB = { "genie::PDFLIB" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtable_ROOT_DICT_PDF() {
  G___ROOT_DICT_PDFLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_string.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_genie.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_geniecLcLEAlgStatus.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_geniecLcLEAlgCmp.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_TVectorTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_TVectorTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_geniecLcLAlgId.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_geniecLcLERgType.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_pairlEstringcOgeniecLcLRegistryItemImUgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_geniecLcLRegistry.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_geniecLcLAlgorithm.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_pairlEstringcOgeniecLcLAlgorithmmUgR.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_geniecLcLEPDF.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_geniecLcLPDFModelI.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_geniecLcLPDF.tagnum = -1 ;
  G___ROOT_DICT_PDFLN_geniecLcLPDFLIB.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtable_ROOT_DICT_PDF() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_string);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_genie),0,-1,0,(char*)NULL,G__setup_memvargenie,G__setup_memfuncgenie);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_geniecLcLEAlgStatus);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_geniecLcLEAlgCmp);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_geniecLcLAlgId);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_geniecLcLERgType);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_pairlEstringcOgeniecLcLRegistryItemImUgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_geniecLcLRegistry);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_geniecLcLAlgorithm);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_pairlEstringcOgeniecLcLAlgorithmmUgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_geniecLcLEPDF);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_geniecLcLPDFModelI),sizeof(genie::PDFModelI),-1,34058,(char*)NULL,G__setup_memvargeniecLcLPDFModelI,G__setup_memfuncgeniecLcLPDFModelI);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_geniecLcLPDF),sizeof(genie::PDF),-1,1792,(char*)NULL,G__setup_memvargeniecLcLPDF,G__setup_memfuncgeniecLcLPDF);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_PDFLN_geniecLcLPDFLIB),sizeof(genie::PDFLIB),-1,34048,(char*)NULL,G__setup_memvargeniecLcLPDFLIB,G__setup_memfuncgeniecLcLPDFLIB);
}
extern "C" void G__cpp_setup_ROOT_DICT_PDF(void) {
  G__check_setup_version(30051515,"G__cpp_setup_ROOT_DICT_PDF()");
  G__set_cpp_environment_ROOT_DICT_PDF();
  G__cpp_setup_tagtable_ROOT_DICT_PDF();

  G__cpp_setup_inheritance_ROOT_DICT_PDF();

  G__cpp_setup_typetable_ROOT_DICT_PDF();

  G__cpp_setup_memvar_ROOT_DICT_PDF();

  G__cpp_setup_memfunc_ROOT_DICT_PDF();
  G__cpp_setup_global_ROOT_DICT_PDF();
  G__cpp_setup_func_ROOT_DICT_PDF();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunc_ROOT_DICT_PDF();
  return;
}
class G__cpp_setup_init_ROOT_DICT_PDF {
  public:
    G__cpp_setup_init_ROOT_DICT_PDF() { G__add_setup_func("_ROOT_DICT_PDF",(G__incsetup)(&G__cpp_setup_ROOT_DICT_PDF)); G__call_setup_funcs(); }
   ~G__cpp_setup_init_ROOT_DICT_PDF() { G__remove_setup_func("_ROOT_DICT_PDF"); }
};
G__cpp_setup_init_ROOT_DICT_PDF G__cpp_setup_initializer_ROOT_DICT_PDF;

