/********************************************************************
* _ROOT_DICT_PDF.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error _ROOT_DICT_PDF.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable_ROOT_DICT_PDF();
extern void G__cpp_setup_inheritance_ROOT_DICT_PDF();
extern void G__cpp_setup_typetable_ROOT_DICT_PDF();
extern void G__cpp_setup_memvar_ROOT_DICT_PDF();
extern void G__cpp_setup_global_ROOT_DICT_PDF();
extern void G__cpp_setup_memfunc_ROOT_DICT_PDF();
extern void G__cpp_setup_func_ROOT_DICT_PDF();
extern void G__set_cpp_environment_ROOT_DICT_PDF();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PDF.h"
#include "PDFLIB.h"
#include "PDFModelI.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G___ROOT_DICT_PDFLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_string;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_genie;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLEAlgStatus;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLEAlgCmp;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_TVectorTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_TVectorTlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLAlgId;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLERgType;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_pairlEstringcOgeniecLcLRegistryItemImUgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLRegistry;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLAlgorithm;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_pairlEstringcOgeniecLcLAlgorithmmUgR;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLEPDF;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLPDFModelI;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLPDF;
extern G__linked_taginfo G___ROOT_DICT_PDFLN_geniecLcLPDFLIB;

/* STUB derived class for protected member access */
