/********************************************************************
* _ROOT_DICT_Numerical.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error _ROOT_DICT_Numerical.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable_ROOT_DICT_Numerical();
extern void G__cpp_setup_inheritance_ROOT_DICT_Numerical();
extern void G__cpp_setup_typetable_ROOT_DICT_Numerical();
extern void G__cpp_setup_memvar_ROOT_DICT_Numerical();
extern void G__cpp_setup_global_ROOT_DICT_Numerical();
extern void G__cpp_setup_memfunc_ROOT_DICT_Numerical();
extern void G__cpp_setup_func_ROOT_DICT_Numerical();
extern void G__set_cpp_environment_ROOT_DICT_Numerical();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BLI2D.h"
#include "GFunc.h"
#include "RandomGen.h"
#include "Spline.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G___ROOT_DICT_NumericalLN_TClass;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_TBuffer;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_TMemberInspector;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_TObject;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_string;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_genie;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_geniecLcLBLI2DGrid;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_geniecLcLBLI2DUnifGrid;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_geniecLcLBLI2DNonUnifGrid;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_TRandom3;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_geniecLcLRandomGen;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_TVectorTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_TVectorTlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_TGraph;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_TSpline3;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_TNtupleD;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_TTree;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_TSQLServer;
extern G__linked_taginfo G___ROOT_DICT_NumericalLN_geniecLcLSpline;

/* STUB derived class for protected member access */
