/********************************************************************
* _ROOT_DICT_GHEP.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error _ROOT_DICT_GHEP.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable_ROOT_DICT_GHEP();
extern void G__cpp_setup_inheritance_ROOT_DICT_GHEP();
extern void G__cpp_setup_typetable_ROOT_DICT_GHEP();
extern void G__cpp_setup_memvar_ROOT_DICT_GHEP();
extern void G__cpp_setup_global_ROOT_DICT_GHEP();
extern void G__cpp_setup_memfunc_ROOT_DICT_GHEP();
extern void G__cpp_setup_func_ROOT_DICT_GHEP();
extern void G__set_cpp_environment_ROOT_DICT_GHEP();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "GHepParticle.h"
#include "GHepRecord.h"
#include "GHepRecordHistory.h"
#include "GHepUtils.h"
#include "GHepVirtualList.h"
#include "GHepVirtualListFolder.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TClass;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TBuffer;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMemberInspector;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TObject;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TRootIOCtor;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TCollection;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_string;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TObjArray;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TClonesArray;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TVectorTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TVectorTlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TVector3;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TLorentzVector;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_genie;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLEGHepStatus;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLGHepParticle;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TSeqCollection;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_TBits;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLEGEvGenMode;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLEKinePhaseSpace;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLERefFrame;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLTarget;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLInitialState;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLEInteractionType;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLEScatteringType;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLProcessInfo;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLEKineVar;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLKinematics;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_maplEgeniecLcLEKineVarcOdoublecOlesslEgeniecLcLEKineVargRcOallocatorlEpairlEconstsPgeniecLcLEKineVarcOdoublegRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLEResonance;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLXclsTag;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLInteraction;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLGHepRecord;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLGHepRecordHistory;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_maplEintcOgeniecLcLGHepRecordmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOgeniecLcLGHepRecordmUgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLutils;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLutilscLcLghep;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLGHepVirtualList;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_geniecLcLGHepVirtualListFolder;
extern G__linked_taginfo G___ROOT_DICT_GHEPLN_maplEstringcOgeniecLcLGHepVirtualListmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLGHepVirtualListmUgRsPgRsPgR;

/* STUB derived class for protected member access */
