//
// File generated by rootcint at Thu Jul 13 14:25:06 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME _ROOT_DICT_BodekYang
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "_ROOT_DICT_BodekYang.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace genie {
   namespace ROOTDict {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void genie_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("genie", 0 /*version*/, "./BYStrucFunc.h", 25,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &genie_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void genie_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

namespace ROOTDict {
   void geniecLcLBYPDF_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void geniecLcLBYPDF_Dictionary();
   static void *new_geniecLcLBYPDF(void *p = 0);
   static void *newArray_geniecLcLBYPDF(Long_t size, void *p);
   static void delete_geniecLcLBYPDF(void *p);
   static void deleteArray_geniecLcLBYPDF(void *p);
   static void destruct_geniecLcLBYPDF(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::genie::BYPDF*)
   {
      ::genie::BYPDF *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::genie::BYPDF),0);
      static ::ROOT::TGenericClassInfo 
         instance("genie::BYPDF", "./BYPDF.h", 25,
                  typeid(::genie::BYPDF), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &geniecLcLBYPDF_Dictionary, isa_proxy, 0,
                  sizeof(::genie::BYPDF) );
      instance.SetNew(&new_geniecLcLBYPDF);
      instance.SetNewArray(&newArray_geniecLcLBYPDF);
      instance.SetDelete(&delete_geniecLcLBYPDF);
      instance.SetDeleteArray(&deleteArray_geniecLcLBYPDF);
      instance.SetDestructor(&destruct_geniecLcLBYPDF);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::genie::BYPDF*)
   {
      return GenerateInitInstanceLocal((::genie::BYPDF*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::genie::BYPDF*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void geniecLcLBYPDF_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::genie::BYPDF*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   void geniecLcLBYStrucFunc_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void geniecLcLBYStrucFunc_Dictionary();
   static void *new_geniecLcLBYStrucFunc(void *p = 0);
   static void *newArray_geniecLcLBYStrucFunc(Long_t size, void *p);
   static void delete_geniecLcLBYStrucFunc(void *p);
   static void deleteArray_geniecLcLBYStrucFunc(void *p);
   static void destruct_geniecLcLBYStrucFunc(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::genie::BYStrucFunc*)
   {
      ::genie::BYStrucFunc *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::genie::BYStrucFunc),0);
      static ::ROOT::TGenericClassInfo 
         instance("genie::BYStrucFunc", "./BYStrucFunc.h", 27,
                  typeid(::genie::BYStrucFunc), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &geniecLcLBYStrucFunc_Dictionary, isa_proxy, 0,
                  sizeof(::genie::BYStrucFunc) );
      instance.SetNew(&new_geniecLcLBYStrucFunc);
      instance.SetNewArray(&newArray_geniecLcLBYStrucFunc);
      instance.SetDelete(&delete_geniecLcLBYStrucFunc);
      instance.SetDeleteArray(&deleteArray_geniecLcLBYStrucFunc);
      instance.SetDestructor(&destruct_geniecLcLBYStrucFunc);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::genie::BYStrucFunc*)
   {
      return GenerateInitInstanceLocal((::genie::BYStrucFunc*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::genie::BYStrucFunc*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void geniecLcLBYStrucFunc_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::genie::BYStrucFunc*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_geniecLcLBYPDF(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genie::BYPDF : new ::genie::BYPDF;
   }
   static void *newArray_geniecLcLBYPDF(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genie::BYPDF[nElements] : new ::genie::BYPDF[nElements];
   }
   // Wrapper around operator delete
   static void delete_geniecLcLBYPDF(void *p) {
      delete ((::genie::BYPDF*)p);
   }
   static void deleteArray_geniecLcLBYPDF(void *p) {
      delete [] ((::genie::BYPDF*)p);
   }
   static void destruct_geniecLcLBYPDF(void *p) {
      typedef ::genie::BYPDF current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::genie::BYPDF

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_geniecLcLBYStrucFunc(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genie::BYStrucFunc : new ::genie::BYStrucFunc;
   }
   static void *newArray_geniecLcLBYStrucFunc(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genie::BYStrucFunc[nElements] : new ::genie::BYStrucFunc[nElements];
   }
   // Wrapper around operator delete
   static void delete_geniecLcLBYStrucFunc(void *p) {
      delete ((::genie::BYStrucFunc*)p);
   }
   static void deleteArray_geniecLcLBYStrucFunc(void *p) {
      delete [] ((::genie::BYStrucFunc*)p);
   }
   static void destruct_geniecLcLBYStrucFunc(void *p) {
      typedef ::genie::BYStrucFunc current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::genie::BYStrucFunc

/********************************************************
* _ROOT_DICT_BodekYang.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtable_ROOT_DICT_BodekYang();

extern "C" void G__set_cpp_environment_ROOT_DICT_BodekYang() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("BYPDF.h");
  G__add_compiledheader("BYStrucFunc.h");
  G__cpp_reset_tagtable_ROOT_DICT_BodekYang();
}
#include <new>
extern "C" int G__cpp_dllrev_ROOT_DICT_BodekYang() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* genie */
static int G___ROOT_DICT_BodekYang_403_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::AlgId*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BodekYang_403_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::Registry*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BodekYang_403_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::Algorithm*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BodekYang_403_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::Target*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BodekYang_403_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::InitialState*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BodekYang_403_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::ProcessInfo*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BodekYang_403_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::Kinematics*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BodekYang_403_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::XclsTag*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BodekYang_403_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::Interaction*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BodekYang_403_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::PDF*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}


/* genie::BYPDF */
static int G___ROOT_DICT_BodekYang_562_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::BYPDF* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genie::BYPDF[n];
     } else {
       p = new((void*) gvp) genie::BYPDF[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genie::BYPDF;
     } else {
       p = new((void*) gvp) genie::BYPDF;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYPDF));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BodekYang_562_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::BYPDF* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new genie::BYPDF(*((string*) G__int(libp->para[0])));
   } else {
     p = new((void*) gvp) genie::BYPDF(*((string*) G__int(libp->para[0])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYPDF));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G___ROOT_DICT_BodekYang_562_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   genie::BYPDF* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new genie::BYPDF(*(genie::BYPDF*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYPDF));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef genie::BYPDF G__TgeniecLcLBYPDF;
static int G___ROOT_DICT_BodekYang_562_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (genie::BYPDF*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((genie::BYPDF*) (soff+(sizeof(genie::BYPDF)*i)))->~G__TgeniecLcLBYPDF();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (genie::BYPDF*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((genie::BYPDF*) (soff))->~G__TgeniecLcLBYPDF();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* genie::BYStrucFunc */
static int G___ROOT_DICT_BodekYang_634_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::BYStrucFunc* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genie::BYStrucFunc[n];
     } else {
       p = new((void*) gvp) genie::BYStrucFunc[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genie::BYStrucFunc;
     } else {
       p = new((void*) gvp) genie::BYStrucFunc;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_BodekYang_634_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::BYStrucFunc* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new genie::BYStrucFunc(*((string*) G__int(libp->para[0])));
   } else {
     p = new((void*) gvp) genie::BYStrucFunc(*((string*) G__int(libp->para[0])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G___ROOT_DICT_BodekYang_634_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   genie::BYStrucFunc* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new genie::BYStrucFunc(*(genie::BYStrucFunc*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef genie::BYStrucFunc G__TgeniecLcLBYStrucFunc;
static int G___ROOT_DICT_BodekYang_634_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (genie::BYStrucFunc*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((genie::BYStrucFunc*) (soff+(sizeof(genie::BYStrucFunc)*i)))->~G__TgeniecLcLBYStrucFunc();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (genie::BYStrucFunc*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((genie::BYStrucFunc*) (soff))->~G__TgeniecLcLBYStrucFunc();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G___ROOT_DICT_BodekYang_634_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::BYStrucFunc* dest = (genie::BYStrucFunc*) G__getstructoffset();
   *dest = *(genie::BYStrucFunc*) libp->para[0].ref;
   const genie::BYStrucFunc& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* genie */

/* genie::BYPDF */

/* genie::BYStrucFunc */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunc_ROOT_DICT_BodekYang {
 public:
  G__Sizep2memfunc_ROOT_DICT_BodekYang(): p(&G__Sizep2memfunc_ROOT_DICT_BodekYang::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunc_ROOT_DICT_BodekYang::*p)();
};

size_t G__get_sizep2memfunc_ROOT_DICT_BodekYang()
{
  G__Sizep2memfunc_ROOT_DICT_BodekYang a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritance_ROOT_DICT_BodekYang() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYPDF))) {
     genie::BYPDF *G__Lderived;
     G__Lderived=(genie::BYPDF*)0x1000;
     {
       genie::PDFModelI *G__Lpbase=(genie::PDFModelI*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYPDF),G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLPDFModelI),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       genie::Algorithm *G__Lpbase=(genie::Algorithm*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYPDF),G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLAlgorithm),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc))) {
     genie::BYStrucFunc *G__Lderived;
     G__Lderived=(genie::BYStrucFunc*)0x1000;
     {
       genie::QPMDISStrucFuncBase *G__Lpbase=(genie::QPMDISStrucFuncBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc),G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLQPMDISStrucFuncBase),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       genie::DISStructureFuncModelI *G__Lpbase=(genie::DISStructureFuncModelI*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc),G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLDISStructureFuncModelI),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       genie::Algorithm *G__Lpbase=(genie::Algorithm*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc),G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLAlgorithm),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetable_ROOT_DICT_BodekYang() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgStatus_t",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEAlgStatus),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgCmp_t",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEAlgCmp),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgType_t",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERgType),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<RgKey,RegistryItemI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,genie::RegistryItemI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,genie::RegistryItemI*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMap",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<RgKey,RegistryItemI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_pairlEstringcOgeniecLcLRegistryItemImUgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMapPair",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_pairlEstringcOgeniecLcLRegistryItemImUgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMapSizeType",107,-1,0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMapIter",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMapConstIter",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<RgKey>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgKeyList",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_vectorlEstringcOallocatorlEstringgRsPgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,Algorithm*>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,genie::Algorithm*>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,genie::Algorithm*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgMap",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgMapIter",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgMapConstIter",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<string,Algorithm*>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_pairlEstringcOgeniecLcLAlgorithmmUgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgMapPair",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_pairlEstringcOgeniecLcLAlgorithmmUgR),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("PDF_t",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEPDF),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RefFrame_t",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERefFrame),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("InteractionType_t",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEInteractionType),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ScatteringType_t",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("KineVar_t",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<KineVar_t,double>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEgeniecLcLEKineVarcOdoublecOlesslEgeniecLcLEKineVargRcOallocatorlEpairlEconstsPgeniecLcLEKineVarcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<genie::EKineVar,double>",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEgeniecLcLEKineVarcOdoublecOlesslEgeniecLcLEKineVargRcOallocatorlEpairlEconstsPgeniecLcLEKineVarcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<genie::EKineVar,double,less<genie::EKineVar> >",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_maplEgeniecLcLEKineVarcOdoublecOlesslEgeniecLcLEKineVargRcOallocatorlEpairlEconstsPgeniecLcLEKineVarcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Resonance_t",117,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),0,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* genie */
static void G__setup_memvargenie(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   {
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEAlgStatus),-1,-2,1,G__FastAllocString(2048).Format("kAlgUndefinedStatus=%lldLL",(long long)genie::kAlgUndefinedStatus).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEAlgStatus),-1,-2,1,G__FastAllocString(2048).Format("kAlgFail=%lldLL",(long long)genie::kAlgFail).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEAlgStatus),-1,-2,1,G__FastAllocString(2048).Format("kAlgSuccess=%lldLL",(long long)genie::kAlgSuccess).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEAlgCmp),-1,-2,1,G__FastAllocString(2048).Format("kAlgCmpUnknown=%lldLL",(long long)genie::kAlgCmpUnknown).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEAlgCmp),-1,-2,1,G__FastAllocString(2048).Format("kAlgCmpIdentical=%lldLL",(long long)genie::kAlgCmpIdentical).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEAlgCmp),-1,-2,1,G__FastAllocString(2048).Format("kAlgCmpDiffConfig=%lldLL",(long long)genie::kAlgCmpDiffConfig).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEAlgCmp),-1,-2,1,G__FastAllocString(2048).Format("kAlgCmpDiffAlg=%lldLL",(long long)genie::kAlgCmpDiffAlg).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgUndefined=%lldLL",(long long)genie::kRgUndefined).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgBool=%lldLL",(long long)genie::kRgBool).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgInt=%lldLL",(long long)genie::kRgInt).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgDbl=%lldLL",(long long)genie::kRgDbl).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgStr=%lldLL",(long long)genie::kRgStr).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgAlg=%lldLL",(long long)genie::kRgAlg).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgH1F=%lldLL",(long long)genie::kRgH1F).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgH2F=%lldLL",(long long)genie::kRgH2F).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgTree=%lldLL",(long long)genie::kRgTree).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERefFrame),-1,-2,1,G__FastAllocString(2048).Format("kRfUndefined=%lldLL",(long long)genie::kRfUndefined).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERefFrame),-1,-2,1,G__FastAllocString(2048).Format("kRfLab=%lldLL",(long long)genie::kRfLab).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERefFrame),-1,-2,1,G__FastAllocString(2048).Format("kRfCM=%lldLL",(long long)genie::kRfCM).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERefFrame),-1,-2,1,G__FastAllocString(2048).Format("kRfHCM=%lldLL",(long long)genie::kRfHCM).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERefFrame),-1,-2,1,G__FastAllocString(2048).Format("kRfTgtRest=%lldLL",(long long)genie::kRfTgtRest).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERefFrame),-1,-2,1,G__FastAllocString(2048).Format("kRfHitNucRest=%lldLL",(long long)genie::kRfHitNucRest).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLERefFrame),-1,-2,1,G__FastAllocString(2048).Format("kRfHitElRest=%lldLL",(long long)genie::kRfHitElRest).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEInteractionType),-1,-2,1,G__FastAllocString(2048).Format("kIntNull=%lldLL",(long long)genie::kIntNull).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEInteractionType),-1,-2,1,G__FastAllocString(2048).Format("kIntEM=%lldLL",(long long)genie::kIntEM).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEInteractionType),-1,-2,1,G__FastAllocString(2048).Format("kIntWeakCC=%lldLL",(long long)genie::kIntWeakCC).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEInteractionType),-1,-2,1,G__FastAllocString(2048).Format("kIntWeakNC=%lldLL",(long long)genie::kIntWeakNC).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEInteractionType),-1,-2,1,G__FastAllocString(2048).Format("kIntWeakMix=%lldLL",(long long)genie::kIntWeakMix).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEInteractionType),-1,-2,1,G__FastAllocString(2048).Format("kIntNDecay=%lldLL",(long long)genie::kIntNDecay).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScNull=%lldLL",(long long)genie::kScNull).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScQuasiElastic=%lldLL",(long long)genie::kScQuasiElastic).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScSingleKaon=%lldLL",(long long)genie::kScSingleKaon).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScDeepInelastic=%lldLL",(long long)genie::kScDeepInelastic).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScResonant=%lldLL",(long long)genie::kScResonant).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScCoherent=%lldLL",(long long)genie::kScCoherent).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScDiffractive=%lldLL",(long long)genie::kScDiffractive).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScNuElectronElastic=%lldLL",(long long)genie::kScNuElectronElastic).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScInverseMuDecay=%lldLL",(long long)genie::kScInverseMuDecay).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScAMNuGamma=%lldLL",(long long)genie::kScAMNuGamma).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScRESNCGamma=%lldLL",(long long)genie::kScRESNCGamma).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScMEC=%lldLL",(long long)genie::kScMEC).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScCoherentElas=%lldLL",(long long)genie::kScCoherentElas).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScInverseBetaDecay=%lldLL",(long long)genie::kScInverseBetaDecay).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScGlashowResonance=%lldLL",(long long)genie::kScGlashowResonance).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType),-1,-2,1,G__FastAllocString(2048).Format("kScIMDAnnihilation=%lldLL",(long long)genie::kScIMDAnnihilation).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVNull=%lldLL",(long long)genie::kKVNull).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVx=%lldLL",(long long)genie::kKVx).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVy=%lldLL",(long long)genie::kKVy).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVQ2=%lldLL",(long long)genie::kKVQ2).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVq2=%lldLL",(long long)genie::kKVq2).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVW=%lldLL",(long long)genie::kKVW).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVt=%lldLL",(long long)genie::kKVt).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVTk=%lldLL",(long long)genie::kKVTk).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVTl=%lldLL",(long long)genie::kKVTl).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVctl=%lldLL",(long long)genie::kKVctl).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVphikq=%lldLL",(long long)genie::kKVphikq).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVSelx=%lldLL",(long long)genie::kKVSelx).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVSely=%lldLL",(long long)genie::kKVSely).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVSelQ2=%lldLL",(long long)genie::kKVSelQ2).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVSelq2=%lldLL",(long long)genie::kKVSelq2).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVSelW=%lldLL",(long long)genie::kKVSelW).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVSelt=%lldLL",(long long)genie::kKVSelt).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVSelTk=%lldLL",(long long)genie::kKVSelTk).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVSelTl=%lldLL",(long long)genie::kKVSelTl).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVSelctl=%lldLL",(long long)genie::kKVSelctl).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVSelphikq=%lldLL",(long long)genie::kKVSelphikq).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVEGamma=%lldLL",(long long)genie::kKVEGamma).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar),-1,-2,1,G__FastAllocString(2048).Format("kKVPhiGamma=%lldLL",(long long)genie::kKVPhiGamma).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kNoResonance=%lldLL",(long long)genie::kNoResonance).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kP33_1232=%lldLL",(long long)genie::kP33_1232).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kS11_1535=%lldLL",(long long)genie::kS11_1535).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kD13_1520=%lldLL",(long long)genie::kD13_1520).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kS11_1650=%lldLL",(long long)genie::kS11_1650).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kD13_1700=%lldLL",(long long)genie::kD13_1700).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kD15_1675=%lldLL",(long long)genie::kD15_1675).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kS31_1620=%lldLL",(long long)genie::kS31_1620).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kD33_1700=%lldLL",(long long)genie::kD33_1700).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kP11_1440=%lldLL",(long long)genie::kP11_1440).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kP33_1600=%lldLL",(long long)genie::kP33_1600).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kP13_1720=%lldLL",(long long)genie::kP13_1720).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kF15_1680=%lldLL",(long long)genie::kF15_1680).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kP31_1910=%lldLL",(long long)genie::kP31_1910).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kP33_1920=%lldLL",(long long)genie::kP33_1920).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kF35_1905=%lldLL",(long long)genie::kF35_1905).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kF37_1950=%lldLL",(long long)genie::kF37_1950).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kP11_1710=%lldLL",(long long)genie::kP11_1710).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance),-1,-2,1,G__FastAllocString(2048).Format("kF17_1970=%lldLL",(long long)genie::kF17_1970).data(),0,(char*)NULL);
   G__memvar_setup((void*)(&genie::kISkipProcessChk),104,0,1,-1,G__defined_typename("UInt_t"),-1,1,"kISkipProcessChk=",0,"/< if set, skip process validity checks");
   G__memvar_setup((void*)(&genie::kISkipKinematicChk),104,0,1,-1,G__defined_typename("UInt_t"),-1,1,"kISkipKinematicChk=",0,"/< if set, skip kinematic validity checks");
   G__memvar_setup((void*)(&genie::kIAssumeFreeNucleon),104,0,1,-1,G__defined_typename("UInt_t"),-1,1,"kIAssumeFreeNucleon=",0,"/<");
   G__memvar_setup((void*)(&genie::kIAssumeFreeElectron),104,0,1,-1,G__defined_typename("UInt_t"),-1,1,"kIAssumeFreeElectron=",0,"/<");
   G__memvar_setup((void*)(&genie::kINoNuclearCorrection),104,0,1,-1,G__defined_typename("UInt_t"),-1,1,"kINoNuclearCorrection=",0,"/< if set, inhibit nuclear corrections ");
   }
   G__tag_memvar_reset();
}


   /* genie::BYPDF */
static void G__setup_memvargeniecLcLBYPDF(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYPDF));
   { genie::BYPDF *p; p=(genie::BYPDF*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLPDFModelI),-1,-1,4,"fBasePDFModel=",0,"/< base (uncorrected) PDF model");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fX0=",0,"/< correction param X0");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fX1=",0,"/< correction param X1");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fX2=",0,"/< correction param X2");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fQ2min=",0,"/< min. Q2 for PDF evaluation");
   }
   G__tag_memvar_reset();
}


   /* genie::BYStrucFunc */
static void G__setup_memvargeniecLcLBYStrucFunc(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc));
   { genie::BYStrucFunc *p; p=(genie::BYStrucFunc*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fA=",0,"/< better scaling var parameter A");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fB=",0,"/< better scaling var parameter B");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fCsU=",0,"/< U-sea K factor parameter ");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fCsD=",0,"/< D-sea K factor parameter ");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fCv1U=",0,"/< U-val K factor parameter ");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fCv2U=",0,"/< U-val K factor parameter ");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fCv1D=",0,"/< D-val K factor parameter ");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fCv2D=",0,"/< D-val K factor parameter ");
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvar_ROOT_DICT_BodekYang() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncgenie(void) {
   /* genie */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_genie));
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_BodekYang_403_0_1, 117, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::AlgId' - 11 - alg", (char*)NULL, (void*) G__func2void( (ostream& (*)(ostream&, const genie::AlgId&))(&genie::operator<<) ), 0);
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_BodekYang_403_0_2, 117, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::Registry' - 11 - registry", (char*)NULL, (void*) G__func2void( (ostream& (*)(ostream&, const genie::Registry&))(&genie::operator<<) ), 0);
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_BodekYang_403_0_3, 117, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::Algorithm' - 11 - alg", (char*)NULL, (void*) G__func2void( (ostream& (*)(ostream&, const genie::Algorithm&))(&genie::operator<<) ), 0);
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_BodekYang_403_0_4, 117, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::Target' - 11 - t", "/< print", (void*) G__func2void( (ostream& (*)(ostream&, const genie::Target&))(&genie::operator<<) ), 0);
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_BodekYang_403_0_5, 117, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::InitialState' - 11 - i", "/< print", (void*) G__func2void( (ostream& (*)(ostream&, const genie::InitialState&))(&genie::operator<<) ), 0);
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_BodekYang_403_0_6, 117, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::ProcessInfo' - 11 - proc", (char*)NULL, (void*) G__func2void( (ostream& (*)(ostream&, const genie::ProcessInfo&))(&genie::operator<<) ), 0);
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_BodekYang_403_0_7, 117, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::Kinematics' - 11 - kine", (char*)NULL, (void*) G__func2void( (ostream& (*)(ostream&, const genie::Kinematics&))(&genie::operator<<) ), 0);
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_BodekYang_403_0_8, 117, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::XclsTag' - 11 - xcls", "/< print", (void*) G__func2void( (ostream& (*)(ostream&, const genie::XclsTag&))(&genie::operator<<) ), 0);
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_BodekYang_403_0_9, 117, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::Interaction' - 11 - i", "/< print", (void*) G__func2void( (ostream& (*)(ostream&, const genie::Interaction&))(&genie::operator<<) ), 0);
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_BodekYang_403_0_10, 117, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::PDF' - 11 - pdf_set", (char*)NULL, (void*) G__func2void( (ostream& (*)(ostream&, const genie::PDF&))(&genie::operator<<) ), 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncgeniecLcLBYPDF(void) {
   /* genie::BYPDF */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYPDF));
   G__memfunc_setup("BYPDF",373,G___ROOT_DICT_BodekYang_562_0_1, 105, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYPDF), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BYPDF",373,G___ROOT_DICT_BodekYang_562_0_2, 105, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYPDF), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - config", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpValence",899,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("DownValence",1110,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("UpSea",478,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("DownSea",689,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Strange",724,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Charm",491,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Bottom",629,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Top",307,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Gluon",517,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AllPDFs",614,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLEPDF), G__defined_typename("genie::PDF_t"), 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 - q2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Configure",930,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'genie::Registry' - 11 - config", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Configure",930,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - config", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LoadConfig",982,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeltaDU",643,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 1, 1, 4, 8, "d - - 0 - x", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("BYPDF", 373, G___ROOT_DICT_BodekYang_562_0_17, (int) ('i'), G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYPDF), -1, 0, 1, 1, 1, 0, "u 'genie::BYPDF' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BYPDF", 499, G___ROOT_DICT_BodekYang_562_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncgeniecLcLBYStrucFunc(void) {
   /* genie::BYStrucFunc */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc));
   G__memfunc_setup("BYStrucFunc",1080,G___ROOT_DICT_BodekYang_634_0_1, 105, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BYStrucFunc",1080,G___ROOT_DICT_BodekYang_634_0_2, 105, G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - config", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Configure",930,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'genie::Registry' - 11 - config", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Configure",930,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - param_set", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadBYParams",1147,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ScalingVar",1002,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 1, 1, 2, 8, "U 'genie::Interaction' - 10 - i", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("KFactors",797,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 5, 1, 2, 8, 
"U 'genie::Interaction' - 10 - i d - - 1 - kuv "
"d - - 1 - kdv d - - 1 - kus "
"d - - 1 - kds", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("BYStrucFunc", 1080, G___ROOT_DICT_BodekYang_634_0_9, (int) ('i'), G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc), -1, 0, 1, 1, 1, 0, "u 'genie::BYStrucFunc' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BYStrucFunc", 1206, G___ROOT_DICT_BodekYang_634_0_10, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G___ROOT_DICT_BodekYang_634_0_11, (int) ('u'), G__get_linked_tagnum(&G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc), -1, 1, 1, 1, 1, 0, "u 'genie::BYStrucFunc' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunc_ROOT_DICT_BodekYang() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_global_ROOT_DICT_BodekYang() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_func_ROOT_DICT_BodekYang() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G___ROOT_DICT_BodekYangLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR = { "basic_ostream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_string = { "string" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_genie = { "genie" , 110 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLEAlgStatus = { "genie::EAlgStatus" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLEAlgCmp = { "genie::EAlgCmp" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLAlgId = { "genie::AlgId" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLERgType = { "genie::ERgType" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR = { "map<string,genie::RegistryItemI*,less<string>,allocator<pair<const string,genie::RegistryItemI*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_pairlEstringcOgeniecLcLRegistryItemImUgR = { "pair<string,genie::RegistryItemI*>" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator = { "map<string,genie::RegistryItemI*,less<string>,allocator<pair<const string,genie::RegistryItemI*> > >::iterator" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLRegistry = { "genie::Registry" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLAlgorithm = { "genie::Algorithm" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR = { "map<string,genie::Algorithm*,less<string>,allocator<pair<const string,genie::Algorithm*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_pairlEstringcOgeniecLcLAlgorithmmUgR = { "pair<string,genie::Algorithm*>" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator = { "map<string,genie::Algorithm*,less<string>,allocator<pair<const string,genie::Algorithm*> > >::iterator" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLEPDF = { "genie::EPDF" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLPDFModelI = { "genie::PDFModelI" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLBYPDF = { "genie::BYPDF" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLERefFrame = { "genie::ERefFrame" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLTarget = { "genie::Target" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLInitialState = { "genie::InitialState" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLEInteractionType = { "genie::EInteractionType" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType = { "genie::EScatteringType" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLProcessInfo = { "genie::ProcessInfo" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar = { "genie::EKineVar" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLKinematics = { "genie::Kinematics" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_maplEgeniecLcLEKineVarcOdoublecOlesslEgeniecLcLEKineVargRcOallocatorlEpairlEconstsPgeniecLcLEKineVarcOdoublegRsPgRsPgR = { "map<genie::EKineVar,double,less<genie::EKineVar>,allocator<pair<const genie::EKineVar,double> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLEResonance = { "genie::EResonance" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLXclsTag = { "genie::XclsTag" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLInteraction = { "genie::Interaction" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLDISStructureFuncModelI = { "genie::DISStructureFuncModelI" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLPDF = { "genie::PDF" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLQPMDISStrucFuncBase = { "genie::QPMDISStrucFuncBase" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc = { "genie::BYStrucFunc" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtable_ROOT_DICT_BodekYang() {
  G___ROOT_DICT_BodekYangLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_string.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_genie.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLEAlgStatus.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLEAlgCmp.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TVectorTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TVectorTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLAlgId.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLERgType.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_pairlEstringcOgeniecLcLRegistryItemImUgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLRegistry.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLAlgorithm.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_pairlEstringcOgeniecLcLAlgorithmmUgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLEPDF.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLPDFModelI.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLBYPDF.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLERefFrame.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLTarget.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLInitialState.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLEInteractionType.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLProcessInfo.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLKinematics.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_maplEgeniecLcLEKineVarcOdoublecOlesslEgeniecLcLEKineVargRcOallocatorlEpairlEconstsPgeniecLcLEKineVarcOdoublegRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLEResonance.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLXclsTag.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLInteraction.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLDISStructureFuncModelI.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLPDF.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLQPMDISStrucFuncBase.tagnum = -1 ;
  G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtable_ROOT_DICT_BodekYang() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_string);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_genie),0,-1,0,(char*)NULL,G__setup_memvargenie,G__setup_memfuncgenie);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLEAlgStatus);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLEAlgCmp);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLAlgId);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLERgType);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_pairlEstringcOgeniecLcLRegistryItemImUgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLRegistry);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLAlgorithm);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_pairlEstringcOgeniecLcLAlgorithmmUgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLEPDF);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLPDFModelI);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLBYPDF),sizeof(genie::BYPDF),-1,34048,(char*)NULL,G__setup_memvargeniecLcLBYPDF,G__setup_memfuncgeniecLcLBYPDF);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLERefFrame);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLTarget);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLInitialState);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLEInteractionType);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLEScatteringType);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLProcessInfo);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLEKineVar);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLKinematics);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_maplEgeniecLcLEKineVarcOdoublecOlesslEgeniecLcLEKineVargRcOallocatorlEpairlEconstsPgeniecLcLEKineVarcOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLEResonance);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLXclsTag);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLInteraction);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLDISStructureFuncModelI);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLPDF);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLQPMDISStrucFuncBase);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_BodekYangLN_geniecLcLBYStrucFunc),sizeof(genie::BYStrucFunc),-1,34048,(char*)NULL,G__setup_memvargeniecLcLBYStrucFunc,G__setup_memfuncgeniecLcLBYStrucFunc);
}
extern "C" void G__cpp_setup_ROOT_DICT_BodekYang(void) {
  G__check_setup_version(30051515,"G__cpp_setup_ROOT_DICT_BodekYang()");
  G__set_cpp_environment_ROOT_DICT_BodekYang();
  G__cpp_setup_tagtable_ROOT_DICT_BodekYang();

  G__cpp_setup_inheritance_ROOT_DICT_BodekYang();

  G__cpp_setup_typetable_ROOT_DICT_BodekYang();

  G__cpp_setup_memvar_ROOT_DICT_BodekYang();

  G__cpp_setup_memfunc_ROOT_DICT_BodekYang();
  G__cpp_setup_global_ROOT_DICT_BodekYang();
  G__cpp_setup_func_ROOT_DICT_BodekYang();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunc_ROOT_DICT_BodekYang();
  return;
}
class G__cpp_setup_init_ROOT_DICT_BodekYang {
  public:
    G__cpp_setup_init_ROOT_DICT_BodekYang() { G__add_setup_func("_ROOT_DICT_BodekYang",(G__incsetup)(&G__cpp_setup_ROOT_DICT_BodekYang)); G__call_setup_funcs(); }
   ~G__cpp_setup_init_ROOT_DICT_BodekYang() { G__remove_setup_func("_ROOT_DICT_BodekYang"); }
};
G__cpp_setup_init_ROOT_DICT_BodekYang G__cpp_setup_initializer_ROOT_DICT_BodekYang;

