#ifndef _GBUILD_H_ 
#define _GBUILD_H_ 
/* 
 * Build information automatically generated by the GENIE installer 
*/ 

#define __GENIE_PYTHIA6_ENABLED__
//#define __GENIE_MYSQL_ENABLED__
#define __GENIE_FLUX_DRIVERS_ENABLED__
#define __GENIE_GEOM_DRIVERS_ENABLED__
//#define __GENIE_LOW_LEVEL_MESG_ENABLED__
//#define __GENIE_VHE_ENABLED__
#define __GENIE_LHAPDF_ENABLED__
//#define __GENIE_CERNLIB_ENABLED__
//#define __GENIE_GSL_ENABLED__
#define __GENIE_USES_LIBXML2_VERSION__ 20706 
#define __GENIE_USES_LOG4CPP_VERSION__ 101 

#endif

