//
// File generated by rootcint at Thu Jul 13 14:25:22 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME _ROOT_DICT_Decay
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "_ROOT_DICT_Decay.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace genie {
   namespace ROOTDict {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void genie_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("genie", 0 /*version*/, "./PythiaDecayer.h", 28,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &genie_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void genie_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

namespace ROOTDict {
   void geniecLcLDecayModelI_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void geniecLcLDecayModelI_Dictionary();
   static void delete_geniecLcLDecayModelI(void *p);
   static void deleteArray_geniecLcLDecayModelI(void *p);
   static void destruct_geniecLcLDecayModelI(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::genie::DecayModelI*)
   {
      ::genie::DecayModelI *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::genie::DecayModelI),0);
      static ::ROOT::TGenericClassInfo 
         instance("genie::DecayModelI", "/users/mouland/Documents/GENIE_NCGamma/src//Decay/DecayModelI.h", 31,
                  typeid(::genie::DecayModelI), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &geniecLcLDecayModelI_Dictionary, isa_proxy, 0,
                  sizeof(::genie::DecayModelI) );
      instance.SetDelete(&delete_geniecLcLDecayModelI);
      instance.SetDeleteArray(&deleteArray_geniecLcLDecayModelI);
      instance.SetDestructor(&destruct_geniecLcLDecayModelI);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::genie::DecayModelI*)
   {
      return GenerateInitInstanceLocal((::genie::DecayModelI*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::genie::DecayModelI*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void geniecLcLDecayModelI_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::genie::DecayModelI*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   void geniecLcLBaryonResonanceDecayer_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void geniecLcLBaryonResonanceDecayer_Dictionary();
   static void *new_geniecLcLBaryonResonanceDecayer(void *p = 0);
   static void *newArray_geniecLcLBaryonResonanceDecayer(Long_t size, void *p);
   static void delete_geniecLcLBaryonResonanceDecayer(void *p);
   static void deleteArray_geniecLcLBaryonResonanceDecayer(void *p);
   static void destruct_geniecLcLBaryonResonanceDecayer(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::genie::BaryonResonanceDecayer*)
   {
      ::genie::BaryonResonanceDecayer *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::genie::BaryonResonanceDecayer),0);
      static ::ROOT::TGenericClassInfo 
         instance("genie::BaryonResonanceDecayer", "./BaryonResonanceDecayer.h", 35,
                  typeid(::genie::BaryonResonanceDecayer), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &geniecLcLBaryonResonanceDecayer_Dictionary, isa_proxy, 0,
                  sizeof(::genie::BaryonResonanceDecayer) );
      instance.SetNew(&new_geniecLcLBaryonResonanceDecayer);
      instance.SetNewArray(&newArray_geniecLcLBaryonResonanceDecayer);
      instance.SetDelete(&delete_geniecLcLBaryonResonanceDecayer);
      instance.SetDeleteArray(&deleteArray_geniecLcLBaryonResonanceDecayer);
      instance.SetDestructor(&destruct_geniecLcLBaryonResonanceDecayer);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::genie::BaryonResonanceDecayer*)
   {
      return GenerateInitInstanceLocal((::genie::BaryonResonanceDecayer*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::genie::BaryonResonanceDecayer*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void geniecLcLBaryonResonanceDecayer_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::genie::BaryonResonanceDecayer*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   void geniecLcLPythiaDecayer_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void geniecLcLPythiaDecayer_Dictionary();
   static void *new_geniecLcLPythiaDecayer(void *p = 0);
   static void *newArray_geniecLcLPythiaDecayer(Long_t size, void *p);
   static void delete_geniecLcLPythiaDecayer(void *p);
   static void deleteArray_geniecLcLPythiaDecayer(void *p);
   static void destruct_geniecLcLPythiaDecayer(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::genie::PythiaDecayer*)
   {
      ::genie::PythiaDecayer *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::genie::PythiaDecayer),0);
      static ::ROOT::TGenericClassInfo 
         instance("genie::PythiaDecayer", "./PythiaDecayer.h", 30,
                  typeid(::genie::PythiaDecayer), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &geniecLcLPythiaDecayer_Dictionary, isa_proxy, 0,
                  sizeof(::genie::PythiaDecayer) );
      instance.SetNew(&new_geniecLcLPythiaDecayer);
      instance.SetNewArray(&newArray_geniecLcLPythiaDecayer);
      instance.SetDelete(&delete_geniecLcLPythiaDecayer);
      instance.SetDeleteArray(&deleteArray_geniecLcLPythiaDecayer);
      instance.SetDestructor(&destruct_geniecLcLPythiaDecayer);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::genie::PythiaDecayer*)
   {
      return GenerateInitInstanceLocal((::genie::PythiaDecayer*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::genie::PythiaDecayer*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void geniecLcLPythiaDecayer_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::genie::PythiaDecayer*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_geniecLcLDecayModelI(void *p) {
      delete ((::genie::DecayModelI*)p);
   }
   static void deleteArray_geniecLcLDecayModelI(void *p) {
      delete [] ((::genie::DecayModelI*)p);
   }
   static void destruct_geniecLcLDecayModelI(void *p) {
      typedef ::genie::DecayModelI current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::genie::DecayModelI

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_geniecLcLPythiaDecayer(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genie::PythiaDecayer : new ::genie::PythiaDecayer;
   }
   static void *newArray_geniecLcLPythiaDecayer(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genie::PythiaDecayer[nElements] : new ::genie::PythiaDecayer[nElements];
   }
   // Wrapper around operator delete
   static void delete_geniecLcLPythiaDecayer(void *p) {
      delete ((::genie::PythiaDecayer*)p);
   }
   static void deleteArray_geniecLcLPythiaDecayer(void *p) {
      delete [] ((::genie::PythiaDecayer*)p);
   }
   static void destruct_geniecLcLPythiaDecayer(void *p) {
      typedef ::genie::PythiaDecayer current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::genie::PythiaDecayer

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_geniecLcLBaryonResonanceDecayer(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genie::BaryonResonanceDecayer : new ::genie::BaryonResonanceDecayer;
   }
   static void *newArray_geniecLcLBaryonResonanceDecayer(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genie::BaryonResonanceDecayer[nElements] : new ::genie::BaryonResonanceDecayer[nElements];
   }
   // Wrapper around operator delete
   static void delete_geniecLcLBaryonResonanceDecayer(void *p) {
      delete ((::genie::BaryonResonanceDecayer*)p);
   }
   static void deleteArray_geniecLcLBaryonResonanceDecayer(void *p) {
      delete [] ((::genie::BaryonResonanceDecayer*)p);
   }
   static void destruct_geniecLcLBaryonResonanceDecayer(void *p) {
      typedef ::genie::BaryonResonanceDecayer current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::genie::BaryonResonanceDecayer

/********************************************************
* _ROOT_DICT_Decay.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtable_ROOT_DICT_Decay();

extern "C" void G__set_cpp_environment_ROOT_DICT_Decay() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("BaryonResonanceDecayer.h");
  G__add_compiledheader("DecayModelI.h");
  G__add_compiledheader("PythiaDecayer.h");
  G__cpp_reset_tagtable_ROOT_DICT_Decay();
}
#include <new>
extern "C" int G__cpp_dllrev_ROOT_DICT_Decay() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* genie */
static int G___ROOT_DICT_Decay_463_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::AlgId*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_Decay_463_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::Registry*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_Decay_463_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = genie::operator<<(*(ostream*) libp->para[0].ref, *(genie::Algorithm*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}


/* genie::DecayModelI */
static int G___ROOT_DICT_Decay_601_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const genie::DecayModelI*) G__getstructoffset())->IsHandled((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_Decay_601_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const genie::DecayModelI*) G__getstructoffset())->Initialize();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_Decay_601_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const genie::DecayModelI*) G__getstructoffset())->Decay(*(genie::DecayerInputs_t*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_Decay_601_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const genie::DecayModelI*) G__getstructoffset())->Weight());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_Decay_601_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((const genie::DecayModelI*) G__getstructoffset())->InhibitDecay((int) G__int(libp->para[0]), (TDecayChannel*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((const genie::DecayModelI*) G__getstructoffset())->InhibitDecay((int) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_Decay_601_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((const genie::DecayModelI*) G__getstructoffset())->UnInhibitDecay((int) G__int(libp->para[0]), (TDecayChannel*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((const genie::DecayModelI*) G__getstructoffset())->UnInhibitDecay((int) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef genie::DecayModelI G__TgeniecLcLDecayModelI;
static int G___ROOT_DICT_Decay_601_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (genie::DecayModelI*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((genie::DecayModelI*) (soff+(sizeof(genie::DecayModelI)*i)))->~G__TgeniecLcLDecayModelI();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (genie::DecayModelI*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((genie::DecayModelI*) (soff))->~G__TgeniecLcLDecayModelI();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G___ROOT_DICT_Decay_601_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::DecayModelI* dest = (genie::DecayModelI*) G__getstructoffset();
   *dest = *(genie::DecayModelI*) libp->para[0].ref;
   const genie::DecayModelI& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* genie::BaryonResonanceDecayer */
static int G___ROOT_DICT_Decay_602_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::BaryonResonanceDecayer* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genie::BaryonResonanceDecayer[n];
     } else {
       p = new((void*) gvp) genie::BaryonResonanceDecayer[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genie::BaryonResonanceDecayer;
     } else {
       p = new((void*) gvp) genie::BaryonResonanceDecayer;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_Decay_602_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::BaryonResonanceDecayer* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new genie::BaryonResonanceDecayer(*((string*) G__int(libp->para[0])));
   } else {
     p = new((void*) gvp) genie::BaryonResonanceDecayer(*((string*) G__int(libp->para[0])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G___ROOT_DICT_Decay_602_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   genie::BaryonResonanceDecayer* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new genie::BaryonResonanceDecayer(*(genie::BaryonResonanceDecayer*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef genie::BaryonResonanceDecayer G__TgeniecLcLBaryonResonanceDecayer;
static int G___ROOT_DICT_Decay_602_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (genie::BaryonResonanceDecayer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((genie::BaryonResonanceDecayer*) (soff+(sizeof(genie::BaryonResonanceDecayer)*i)))->~G__TgeniecLcLBaryonResonanceDecayer();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (genie::BaryonResonanceDecayer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((genie::BaryonResonanceDecayer*) (soff))->~G__TgeniecLcLBaryonResonanceDecayer();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G___ROOT_DICT_Decay_602_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::BaryonResonanceDecayer* dest = (genie::BaryonResonanceDecayer*) G__getstructoffset();
   *dest = *(genie::BaryonResonanceDecayer*) libp->para[0].ref;
   const genie::BaryonResonanceDecayer& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* genie::PythiaDecayer */
static int G___ROOT_DICT_Decay_628_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::PythiaDecayer* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genie::PythiaDecayer[n];
     } else {
       p = new((void*) gvp) genie::PythiaDecayer[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genie::PythiaDecayer;
     } else {
       p = new((void*) gvp) genie::PythiaDecayer;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_Decay_628_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::PythiaDecayer* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new genie::PythiaDecayer(*((string*) G__int(libp->para[0])));
   } else {
     p = new((void*) gvp) genie::PythiaDecayer(*((string*) G__int(libp->para[0])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G___ROOT_DICT_Decay_628_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   genie::PythiaDecayer* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new genie::PythiaDecayer(*(genie::PythiaDecayer*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef genie::PythiaDecayer G__TgeniecLcLPythiaDecayer;
static int G___ROOT_DICT_Decay_628_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (genie::PythiaDecayer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((genie::PythiaDecayer*) (soff+(sizeof(genie::PythiaDecayer)*i)))->~G__TgeniecLcLPythiaDecayer();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (genie::PythiaDecayer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((genie::PythiaDecayer*) (soff))->~G__TgeniecLcLPythiaDecayer();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G___ROOT_DICT_Decay_628_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genie::PythiaDecayer* dest = (genie::PythiaDecayer*) G__getstructoffset();
   *dest = *(genie::PythiaDecayer*) libp->para[0].ref;
   const genie::PythiaDecayer& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* genie */

/* genie::DecayModelI */

/* genie::BaryonResonanceDecayer */

/* genie::PythiaDecayer */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunc_ROOT_DICT_Decay {
 public:
  G__Sizep2memfunc_ROOT_DICT_Decay(): p(&G__Sizep2memfunc_ROOT_DICT_Decay::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunc_ROOT_DICT_Decay::*p)();
};

size_t G__get_sizep2memfunc_ROOT_DICT_Decay()
{
  G__Sizep2memfunc_ROOT_DICT_Decay a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritance_ROOT_DICT_Decay() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLDecayModelI))) {
     genie::DecayModelI *G__Lderived;
     G__Lderived=(genie::DecayModelI*)0x1000;
     {
       genie::Algorithm *G__Lpbase=(genie::Algorithm*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLDecayModelI),G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLAlgorithm),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer))) {
     genie::BaryonResonanceDecayer *G__Lderived;
     G__Lderived=(genie::BaryonResonanceDecayer*)0x1000;
     {
       genie::DecayModelI *G__Lpbase=(genie::DecayModelI*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer),G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLDecayModelI),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       genie::Algorithm *G__Lpbase=(genie::Algorithm*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer),G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLAlgorithm),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer))) {
     genie::PythiaDecayer *G__Lderived;
     G__Lderived=(genie::PythiaDecayer*)0x1000;
     {
       genie::DecayModelI *G__Lpbase=(genie::DecayModelI*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer),G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLDecayModelI),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       genie::Algorithm *G__Lpbase=(genie::Algorithm*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer),G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLAlgorithm),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetable_ROOT_DICT_Decay() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgStatus_t",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLEAlgStatus),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgCmp_t",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLEAlgCmp),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgType_t",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLERgType),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<RgKey,RegistryItemI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,genie::RegistryItemI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,genie::RegistryItemI*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMap",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<RgKey,RegistryItemI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_pairlEstringcOgeniecLcLRegistryItemImUgR),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMapPair",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_pairlEstringcOgeniecLcLRegistryItemImUgR),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMapSizeType",107,-1,0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMapIter",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgIMapConstIter",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<RgKey>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RgKeyList",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_vectorlEstringcOallocatorlEstringgRsPgR),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,Algorithm*>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,genie::Algorithm*>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,genie::Algorithm*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgMap",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgMapIter",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgMapConstIter",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<string,Algorithm*>",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_pairlEstringcOgeniecLcLAlgorithmmUgR),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AlgMapPair",117,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_pairlEstringcOgeniecLcLAlgorithmmUgR),0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* genie */
static void G__setup_memvargenie(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   {
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLEAlgStatus),-1,-2,1,G__FastAllocString(2048).Format("kAlgUndefinedStatus=%lldLL",(long long)genie::kAlgUndefinedStatus).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLEAlgStatus),-1,-2,1,G__FastAllocString(2048).Format("kAlgFail=%lldLL",(long long)genie::kAlgFail).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLEAlgStatus),-1,-2,1,G__FastAllocString(2048).Format("kAlgSuccess=%lldLL",(long long)genie::kAlgSuccess).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLEAlgCmp),-1,-2,1,G__FastAllocString(2048).Format("kAlgCmpUnknown=%lldLL",(long long)genie::kAlgCmpUnknown).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLEAlgCmp),-1,-2,1,G__FastAllocString(2048).Format("kAlgCmpIdentical=%lldLL",(long long)genie::kAlgCmpIdentical).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLEAlgCmp),-1,-2,1,G__FastAllocString(2048).Format("kAlgCmpDiffConfig=%lldLL",(long long)genie::kAlgCmpDiffConfig).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLEAlgCmp),-1,-2,1,G__FastAllocString(2048).Format("kAlgCmpDiffAlg=%lldLL",(long long)genie::kAlgCmpDiffAlg).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgUndefined=%lldLL",(long long)genie::kRgUndefined).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgBool=%lldLL",(long long)genie::kRgBool).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgInt=%lldLL",(long long)genie::kRgInt).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgDbl=%lldLL",(long long)genie::kRgDbl).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgStr=%lldLL",(long long)genie::kRgStr).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgAlg=%lldLL",(long long)genie::kRgAlg).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgH1F=%lldLL",(long long)genie::kRgH1F).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgH2F=%lldLL",(long long)genie::kRgH2F).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLERgType),-1,-2,1,G__FastAllocString(2048).Format("kRgTree=%lldLL",(long long)genie::kRgTree).data(),0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* genie::DecayModelI */
static void G__setup_memvargeniecLcLDecayModelI(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLDecayModelI));
   { genie::DecayModelI *p; p=(genie::DecayModelI*)0x1000; if (p) { }
   }
   G__tag_memvar_reset();
}


   /* genie::BaryonResonanceDecayer */
static void G__setup_memvargeniecLcLBaryonResonanceDecayer(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer));
   { genie::BaryonResonanceDecayer *p; p=(genie::BaryonResonanceDecayer*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TGenPhaseSpace),-1,-1,4,"fPhaseSpaceGenerator=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fWeight=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"fGenerateWeighted=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* genie::PythiaDecayer */
static void G__setup_memvargeniecLcLPythiaDecayer(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer));
   { genie::PythiaDecayer *p; p=(genie::PythiaDecayer*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TPythia6),-1,-1,4,"fPythia=",0,"/< PYTHIA6 wrapper class");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fWeight=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvar_ROOT_DICT_Decay() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncgenie(void) {
   /* genie */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_genie));
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_Decay_463_0_1, 117, G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::AlgId' - 11 - alg", (char*)NULL, (void*) G__func2void( (ostream& (*)(ostream&, const genie::AlgId&))(&genie::operator<<) ), 0);
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_Decay_463_0_2, 117, G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::Registry' - 11 - registry", (char*)NULL, (void*) G__func2void( (ostream& (*)(ostream&, const genie::Registry&))(&genie::operator<<) ), 0);
   G__memfunc_setup("operator<<",996,G___ROOT_DICT_Decay_463_0_3, 117, G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - stream u 'genie::Algorithm' - 11 - alg", (char*)NULL, (void*) G__func2void( (ostream& (*)(ostream&, const genie::Algorithm&))(&genie::operator<<) ), 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncgeniecLcLDecayModelI(void) {
   /* genie::DecayModelI */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLDecayModelI));
   G__memfunc_setup("IsHandled",876,G___ROOT_DICT_Decay_601_0_1, 103, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - pdgc", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("Initialize",1042,G___ROOT_DICT_Decay_601_0_2, 121, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("Decay",486,G___ROOT_DICT_Decay_601_0_3, 85, G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TClonesArray), -1, 0, 1, 1, 1, 8, "u 'genie::DecayerInputs_t' - 11 - inp", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("Weight",616,G___ROOT_DICT_Decay_601_0_4, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("InhibitDecay",1197,G___ROOT_DICT_Decay_601_0_5, 121, -1, -1, 0, 2, 1, 1, 8, 
"i - - 0 - pdgc U 'TDecayChannel' - 0 '0' dc", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("UnInhibitDecay",1392,G___ROOT_DICT_Decay_601_0_6, 121, -1, -1, 0, 2, 1, 1, 8, 
"i - - 0 - pdgc U 'TDecayChannel' - 0 '0' dc", (char*)NULL, (void*) NULL, 3);
   // automatic destructor
   G__memfunc_setup("~DecayModelI", 1182, G___ROOT_DICT_Decay_601_0_10, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G___ROOT_DICT_Decay_601_0_11, (int) ('u'), G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLDecayModelI), -1, 1, 1, 1, 1, 0, "u 'genie::DecayModelI' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncgeniecLcLBaryonResonanceDecayer(void) {
   /* genie::BaryonResonanceDecayer */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer));
   G__memfunc_setup("BaryonResonanceDecayer",2246,G___ROOT_DICT_Decay_602_0_1, 105, G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BaryonResonanceDecayer",2246,G___ROOT_DICT_Decay_602_0_2, 105, G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - config", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsHandled",876,(G__InterfaceMethod) NULL,103, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - pdgc", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Initialize",1042,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Decay",486,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TClonesArray), -1, 0, 1, 1, 1, 8, "u 'genie::DecayerInputs_t' - 11 - inp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Weight",616,(G__InterfaceMethod) NULL,100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InhibitDecay",1197,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 8, 
"i - - 0 - pdg U 'TDecayChannel' - 0 '0' dc", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("UnInhibitDecay",1392,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 8, 
"i - - 0 - pdg U 'TDecayChannel' - 0 '0' dc", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Configure",930,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'genie::Registry' - 11 - config", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Configure",930,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - config", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LoadConfig",982,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DecayExclusive",1438,(G__InterfaceMethod) NULL, 85, G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TClonesArray), -1, 0, 3, 1, 4, 8, 
"i - - 0 - pdgc u 'TLorentzVector' - 1 - p "
"U 'TDecayChannel' - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FinalStateMass",1407,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 1, 1, 4, 8, "U 'TDecayChannel' - 0 - channel", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("BaryonResonanceDecayer", 2246, G___ROOT_DICT_Decay_602_0_14, (int) ('i'), 
G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer), -1, 0, 1, 1, 1, 0, "u 'genie::BaryonResonanceDecayer' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BaryonResonanceDecayer", 2372, G___ROOT_DICT_Decay_602_0_15, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G___ROOT_DICT_Decay_602_0_16, (int) ('u'), G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer), -1, 1, 1, 1, 1, 0, "u 'genie::BaryonResonanceDecayer' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncgeniecLcLPythiaDecayer(void) {
   /* genie::PythiaDecayer */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer));
   G__memfunc_setup("PythiaDecayer",1324,G___ROOT_DICT_Decay_628_0_1, 105, G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PythiaDecayer",1324,G___ROOT_DICT_Decay_628_0_2, 105, G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - config", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsHandled",876,(G__InterfaceMethod) NULL,103, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - pdgc", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Initialize",1042,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Decay",486,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_TClonesArray), -1, 0, 1, 1, 1, 8, "u 'genie::DecayerInputs_t' - 11 - inp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Weight",616,(G__InterfaceMethod) NULL,100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InhibitDecay",1197,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 8, 
"i - - 0 - pdg U 'TDecayChannel' - 0 '0' dc", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("UnInhibitDecay",1392,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 8, 
"i - - 0 - pdg U 'TDecayChannel' - 0 '0' dc", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Configure",930,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'genie::Registry' - 11 - config", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Configure",930,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - config", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LoadConfig",982,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SumBR",457,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 1, 1, 4, 8, "i - - 0 - kc", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FindPythiaDecayChannel",2191,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 2, 1, 4, 8, 
"i - - 0 - kc U 'TDecayChannel' - 0 - dc", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MatchDecayChannels",1791,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 2, 1, 4, 8, 
"i - - 0 - ichannel U 'TDecayChannel' - 0 - dc", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("PythiaDecayer", 1324, G___ROOT_DICT_Decay_628_0_15, (int) ('i'), G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer), -1, 0, 1, 1, 1, 0, "u 'genie::PythiaDecayer' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PythiaDecayer", 1450, G___ROOT_DICT_Decay_628_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G___ROOT_DICT_Decay_628_0_17, (int) ('u'), G__get_linked_tagnum(&G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer), -1, 1, 1, 1, 1, 0, "u 'genie::PythiaDecayer' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunc_ROOT_DICT_Decay() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_global_ROOT_DICT_Decay() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_func_ROOT_DICT_Decay() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G___ROOT_DICT_DecayLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR = { "basic_ostream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_string = { "string" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TClonesArray = { "TClonesArray" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TLorentzVector = { "TLorentzVector" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TGenPhaseSpace = { "TGenPhaseSpace" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TDecayChannel = { "TDecayChannel" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_genie = { "genie" , 110 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLEAlgStatus = { "genie::EAlgStatus" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLEAlgCmp = { "genie::EAlgCmp" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLAlgId = { "genie::AlgId" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLERgType = { "genie::ERgType" , 101 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR = { "map<string,genie::RegistryItemI*,less<string>,allocator<pair<const string,genie::RegistryItemI*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_pairlEstringcOgeniecLcLRegistryItemImUgR = { "pair<string,genie::RegistryItemI*>" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator = { "map<string,genie::RegistryItemI*,less<string>,allocator<pair<const string,genie::RegistryItemI*> > >::iterator" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLRegistry = { "genie::Registry" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLAlgorithm = { "genie::Algorithm" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR = { "map<string,genie::Algorithm*,less<string>,allocator<pair<const string,genie::Algorithm*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_pairlEstringcOgeniecLcLAlgorithmmUgR = { "pair<string,genie::Algorithm*>" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator = { "map<string,genie::Algorithm*,less<string>,allocator<pair<const string,genie::Algorithm*> > >::iterator" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLDecayerInputs_t = { "genie::DecayerInputs_t" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLDecayModelI = { "genie::DecayModelI" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer = { "genie::BaryonResonanceDecayer" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_TPythia6 = { "TPythia6" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer = { "genie::PythiaDecayer" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtable_ROOT_DICT_Decay() {
  G___ROOT_DICT_DecayLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_string.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TClonesArray.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TVectorTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TVectorTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TLorentzVector.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TGenPhaseSpace.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TDecayChannel.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_genie.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_geniecLcLEAlgStatus.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_geniecLcLEAlgCmp.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_geniecLcLAlgId.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_geniecLcLERgType.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_pairlEstringcOgeniecLcLRegistryItemImUgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_geniecLcLRegistry.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_geniecLcLAlgorithm.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_pairlEstringcOgeniecLcLAlgorithmmUgR.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_geniecLcLDecayerInputs_t.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_geniecLcLDecayModelI.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_TPythia6.tagnum = -1 ;
  G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtable_ROOT_DICT_Decay() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_string);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TClonesArray);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TLorentzVector);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TGenPhaseSpace);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TDecayChannel);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_genie),0,-1,0,(char*)NULL,G__setup_memvargenie,G__setup_memfuncgenie);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_geniecLcLEAlgStatus);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_geniecLcLEAlgCmp);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_geniecLcLAlgId);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_geniecLcLERgType);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_pairlEstringcOgeniecLcLRegistryItemImUgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_geniecLcLRegistry);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_geniecLcLAlgorithm);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_pairlEstringcOgeniecLcLAlgorithmmUgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_geniecLcLDecayerInputs_t);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_geniecLcLDecayModelI),sizeof(genie::DecayModelI),-1,34054,(char*)NULL,G__setup_memvargeniecLcLDecayModelI,G__setup_memfuncgeniecLcLDecayModelI);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer),sizeof(genie::BaryonResonanceDecayer),-1,34048,(char*)NULL,G__setup_memvargeniecLcLBaryonResonanceDecayer,G__setup_memfuncgeniecLcLBaryonResonanceDecayer);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_TPythia6);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer),sizeof(genie::PythiaDecayer),-1,34048,(char*)NULL,G__setup_memvargeniecLcLPythiaDecayer,G__setup_memfuncgeniecLcLPythiaDecayer);
}
extern "C" void G__cpp_setup_ROOT_DICT_Decay(void) {
  G__check_setup_version(30051515,"G__cpp_setup_ROOT_DICT_Decay()");
  G__set_cpp_environment_ROOT_DICT_Decay();
  G__cpp_setup_tagtable_ROOT_DICT_Decay();

  G__cpp_setup_inheritance_ROOT_DICT_Decay();

  G__cpp_setup_typetable_ROOT_DICT_Decay();

  G__cpp_setup_memvar_ROOT_DICT_Decay();

  G__cpp_setup_memfunc_ROOT_DICT_Decay();
  G__cpp_setup_global_ROOT_DICT_Decay();
  G__cpp_setup_func_ROOT_DICT_Decay();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunc_ROOT_DICT_Decay();
  return;
}
class G__cpp_setup_init_ROOT_DICT_Decay {
  public:
    G__cpp_setup_init_ROOT_DICT_Decay() { G__add_setup_func("_ROOT_DICT_Decay",(G__incsetup)(&G__cpp_setup_ROOT_DICT_Decay)); G__call_setup_funcs(); }
   ~G__cpp_setup_init_ROOT_DICT_Decay() { G__remove_setup_func("_ROOT_DICT_Decay"); }
};
G__cpp_setup_init_ROOT_DICT_Decay G__cpp_setup_initializer_ROOT_DICT_Decay;

