/********************************************************************
* _ROOT_DICT_Decay.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error _ROOT_DICT_Decay.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable_ROOT_DICT_Decay();
extern void G__cpp_setup_inheritance_ROOT_DICT_Decay();
extern void G__cpp_setup_typetable_ROOT_DICT_Decay();
extern void G__cpp_setup_memvar_ROOT_DICT_Decay();
extern void G__cpp_setup_global_ROOT_DICT_Decay();
extern void G__cpp_setup_memfunc_ROOT_DICT_Decay();
extern void G__cpp_setup_func_ROOT_DICT_Decay();
extern void G__set_cpp_environment_ROOT_DICT_Decay();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BaryonResonanceDecayer.h"
#include "DecayModelI.h"
#include "PythiaDecayer.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G___ROOT_DICT_DecayLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_string;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TClonesArray;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TVectorTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TVectorTlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TLorentzVector;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TGenPhaseSpace;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TDecayChannel;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_genie;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLEAlgStatus;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLEAlgCmp;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLAlgId;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLERgType;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_pairlEstringcOgeniecLcLRegistryItemImUgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLRegistry;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLAlgorithm;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_pairlEstringcOgeniecLcLAlgorithmmUgR;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_maplEstringcOgeniecLcLAlgorithmmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLAlgorithmmUgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLDecayerInputs_t;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLDecayModelI;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLBaryonResonanceDecayer;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_TPythia6;
extern G__linked_taginfo G___ROOT_DICT_DecayLN_geniecLcLPythiaDecayer;

/* STUB derived class for protected member access */
