/********************************************************************
* _ROOT_DICT_Registry.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error _ROOT_DICT_Registry.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable_ROOT_DICT_Registry();
extern void G__cpp_setup_inheritance_ROOT_DICT_Registry();
extern void G__cpp_setup_typetable_ROOT_DICT_Registry();
extern void G__cpp_setup_memvar_ROOT_DICT_Registry();
extern void G__cpp_setup_global_ROOT_DICT_Registry();
extern void G__cpp_setup_memfunc_ROOT_DICT_Registry();
extern void G__cpp_setup_func_ROOT_DICT_Registry();
extern void G__set_cpp_environment_ROOT_DICT_Registry();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Registry.h"
#include "RegistryItem.h"
#include "RegistryItemTypeDef.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G___ROOT_DICT_RegistryLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_string;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_genie;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_geniecLcLERgType;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_geniecLcLRegistryItemI;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_TH1F;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_TH2F;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_TTree;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_RgAlg;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_TFolder;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_pairlEstringcOgeniecLcLRegistryItemImUgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_maplEstringcOgeniecLcLRegistryItemImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOgeniecLcLRegistryItemImUgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_geniecLcLRegistry;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_geniecLcLRegistryItemlEboolgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_geniecLcLRegistryItemlEintgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_geniecLcLRegistryItemlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_geniecLcLRegistryItemlEstringgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_geniecLcLRegistryItemlERgAlggR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_geniecLcLRegistryItemlETH1FmUgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_geniecLcLRegistryItemlETH2FmUgR;
extern G__linked_taginfo G___ROOT_DICT_RegistryLN_geniecLcLRegistryItemlETTreemUgR;

/* STUB derived class for protected member access */
typedef genie::RegistryItem<bool> G__geniecLcLRegistryItemlEboolgR;
typedef genie::RegistryItem<int> G__geniecLcLRegistryItemlEintgR;
typedef genie::RegistryItem<double> G__geniecLcLRegistryItemlEdoublegR;
typedef genie::RegistryItem<string> G__geniecLcLRegistryItemlEstringgR;
typedef genie::RegistryItem<RgAlg> G__geniecLcLRegistryItemlERgAlggR;
typedef genie::RegistryItem<TH1F*> G__geniecLcLRegistryItemlETH1FmUgR;
typedef genie::RegistryItem<TH2F*> G__geniecLcLRegistryItemlETH2FmUgR;
typedef genie::RegistryItem<TTree*> G__geniecLcLRegistryItemlETTreemUgR;
