/********************************************************************
* _ROOT_DICT_Interaction.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error _ROOT_DICT_Interaction.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable_ROOT_DICT_Interaction();
extern void G__cpp_setup_inheritance_ROOT_DICT_Interaction();
extern void G__cpp_setup_typetable_ROOT_DICT_Interaction();
extern void G__cpp_setup_memvar_ROOT_DICT_Interaction();
extern void G__cpp_setup_global_ROOT_DICT_Interaction();
extern void G__cpp_setup_memfunc_ROOT_DICT_Interaction();
extern void G__cpp_setup_func_ROOT_DICT_Interaction();
extern void G__set_cpp_environment_ROOT_DICT_Interaction();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "InitialState.h"
#include "Interaction.h"
#include "Kinematics.h"
#include "KPhaseSpace.h"
#include "ProcessInfo.h"
#include "Target.h"
#include "XclsTag.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TClass;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TBuffer;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMemberInspector;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TObject;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TRootIOCtor;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_string;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TParticlePDG;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TVectorTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TVectorTlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_TLorentzVector;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_genie;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_geniecLcLERefFrame;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_geniecLcLTarget;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_geniecLcLInitialState;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_geniecLcLEInteractionType;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_geniecLcLEScatteringType;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_geniecLcLProcessInfo;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_geniecLcLEKineVar;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_geniecLcLKinematics;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_maplEgeniecLcLEKineVarcOdoublecOlesslEgeniecLcLEKineVargRcOallocatorlEpairlEconstsPgeniecLcLEKineVarcOdoublegRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_geniecLcLEResonance;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_geniecLcLXclsTag;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_geniecLcLRange1D_t;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_geniecLcLInteraction;
extern G__linked_taginfo G___ROOT_DICT_InteractionLN_geniecLcLKPhaseSpace;

/* STUB derived class for protected member access */
