/********************************************************************
* _ROOT_DICT_PDG.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error _ROOT_DICT_PDG.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable_ROOT_DICT_PDG();
extern void G__cpp_setup_inheritance_ROOT_DICT_PDG();
extern void G__cpp_setup_typetable_ROOT_DICT_PDG();
extern void G__cpp_setup_memvar_ROOT_DICT_PDG();
extern void G__cpp_setup_global_ROOT_DICT_PDG();
extern void G__cpp_setup_memfunc_ROOT_DICT_PDG();
extern void G__cpp_setup_func_ROOT_DICT_PDG();
extern void G__set_cpp_environment_ROOT_DICT_PDG();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PDGCodeList.h"
#include "PDGLibrary.h"
#include "PDGUtils.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G___ROOT_DICT_PDGLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G___ROOT_DICT_PDGLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G___ROOT_DICT_PDGLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_PDGLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_PDGLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_PDGLN_genie;
extern G__linked_taginfo G___ROOT_DICT_PDGLN_geniecLcLPDGCodeList;
extern G__linked_taginfo G___ROOT_DICT_PDGLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_PDGLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator;
extern G__linked_taginfo G___ROOT_DICT_PDGLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_PDGLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G___ROOT_DICT_PDGLN_TParticlePDG;
extern G__linked_taginfo G___ROOT_DICT_PDGLN_TDatabasePDG;
extern G__linked_taginfo G___ROOT_DICT_PDGLN_geniecLcLPDGLibrary;
extern G__linked_taginfo G___ROOT_DICT_PDGLN_geniecLcLpdg;

/* STUB derived class for protected member access */
